### ISSUE TITLE
"IF" goes always the same path

### ISSUE THREAD

**Issue by soshial** [android/play-billing-samples#107]
billingResponseCode will always be `BillingResponse.OK` in this SWITCH statement: https://github.com/googlesamples/android-play-billing/blob/8aa9f362ff66cf8220b8fc9bd6526fd78dd76a48/TrivialDrive_v2/shared-module/src/main/java/com/example/billingmodule/skulist/AcquireFragment.java#L136-L137

Method `displayAnErrorIfNeeded()` here https://github.com/googlesamples/android-play-billing/blob/8aa9f362ff66cf8220b8fc9bd6526fd78dd76a48/TrivialDrive_v2/shared-module/src/main/java/com/example/billingmodule/skulist/AcquireFragment.java#L204, is called from if https://github.com/googlesamples/android-play-billing/blob/8aa9f362ff66cf8220b8fc9bd6526fd78dd76a48/TrivialDrive_v2/shared-module/src/main/java/com/example/billingmodule/skulist/AcquireFragment.java#L187-L191 and that is why it is always`responseCode == BillingResponse.OK`!

**Comment by calren** [comment]
Closing this issue as TrivialDrive_v2 has now been [deprecated](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440)
