### ISSUE TITLE
orderId field not incrementing AND lapsed state date calculation?

### ISSUE THREAD

**Issue by mutablestudio** [android/play-billing-samples#110]
Three issues/questions which are related to Billing and this repo.

1) The auto renew subscription orderId field for test purchases doesn't append 0,1,2 when they they auto renew, like they are supposed to according to google docs. is this an issue everyone is facing or is it a bug?

GPA.1234-5678-9012-34567 (base order number)
GPA.1234-5678-9012-34567..0 (first recurrence orderID)
GPA.1234-5678-9012-34567..1 (second recurrence orderID)
GPA.1234-5678-9012-34567..2 (third recurrence orderID)

I only see the base order number returned even after a test purchase renews (I know it's renewing because I receive the email in my gmail for that device's gmail account).

2) The google docs state that, for the 'autoRenewing' boolean field, "If you offer a grace period, this value remains set to true for all subscriptions, as long as the grace period has not lapsed. The next billing date is extended dynamically every day until the end of the grace period or until the user fixes their payment method.". How can we determine when the lapsed state starts if the billing date keeps getting extended every day? For example, we want to know the date of the first day that the subscription went into a lapsed state.

3) expire_date for a subscription doesn't seem to be represented in the INAPP_PURCHASE_DATA fields. Is there another API call I can make to get more info or is this the only data I'll receive from purchase queries? I can calculate it from the subscription period but I want to make sure I'm not missing any relevant data.

TIA.

**Comment by calren** [comment]
@mutablestudio sorry this question wasn't addressed earlier, but given that the billing library has changed a bit since when this issue was first opened, I'm going to go ahead and close this issue. Feel free to open another issue if you find any issues with the samples in this repository. If you have a question regarding the billing library itself, it's best to post the question on Stackoverflow with the tag 'android-billing'.
