### ISSUE TITLE
Signature verification does not belong to handleActivityResult?

### ISSUE THREAD

**Issue by Bevor** [android/play-billing-samples#114]
In `handleActivityResult` you check `Security.verifyPurchase(...)` inside the` if (resultCode == Activity.RESULT_OK && responseCode == BILLING_RESPONSE_RESULT_OK)` part. 
In my opinion this is wrong, because when result == OK and response code == OK, then the Purchase was confirmed by Google, since this is the result of the Google Play interaction Activity. What is the purpose of the signature verification check here, because this check must always be true (otherwise there wouldn't be a valid purchase from Google)?

**Comment by Misti26** [comment]
Misti Hinojos

**Comment by calren** [comment]
Closing this issue as TrivialDrive_v2 has now been [deprecated](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440)
