### ISSUE TITLE
RuntimeException: Package manager has died

### ISSUE THREAD

**Issue by Albul** [android/play-billing-samples#123]
I'm constantly getting this on many kind of devices:

**Exception java.lang.RuntimeException: Package manager has died**
android.app.ApplicationPackageManager.queryIntentServicesAsUser (ApplicationPackageManager.java:650)
android.app.ApplicationPackageManager.queryIntentServices (ApplicationPackageManager.java:656)
com.android.billingclient.api.BillingClientImpl.startConnection (BillingClientImpl.java:219)
com.abdula.pranabreath.common.billing.BillingServiceImpl.startServiceConnection (BillingServiceImpl.java:113)
com.abdula.pranabreath.common.billing.BillingServiceImpl.access$000 (BillingServiceImpl.java:38)
com.abdula.pranabreath.common.billing.BillingServiceImpl$2$1.run (BillingServiceImpl.java:137)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5254)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:902)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:697)
arrow_drop_down

**Caused by android.os.DeadObjectException:**
android.os.BinderProxy.transactNative (BinderProxy.java)
android.os.BinderProxy.transact (BinderProxy.java:496)
android.content.pm.IPackageManager$Stub$Proxy.queryIntentServices (IPackageManager.java:2629)
android.app.ApplicationPackageManager.queryIntentServicesAsUser (ApplicationPackageManager.java:644)
android.app.ApplicationPackageManager.queryIntentServices (ApplicationPackageManager.java:656)
com.android.billingclient.api.BillingClientImpl.startConnection (BillingClientImpl.java:219)
com.abdula.pranabreath.common.billing.BillingServiceImpl.startServiceConnection (BillingServiceImpl.java:113)
com.abdula.pranabreath.common.billing.BillingServiceImpl.access$000 (BillingServiceImpl.java:38)
com.abdula.pranabreath.common.billing.BillingServiceImpl$2$1.run (BillingServiceImpl.java:137)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5254)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:902)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:697)

![crash](https://user-images.githubusercontent.com/1837809/37210556-d32f369e-23b1-11e8-9964-b5afd9162128.png)

**Comment by gajendrakumartwinwal** [comment]
**Facing same crash below are logs for the same.**
Fatal Exception: java.lang.RuntimeException: Package manager has died
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:146)
       at com.google.android.gms.common.zzp.isGooglePlayServicesAvailable(Unknown Source)
       at com.google.android.gms.common.zzf.isGooglePlayServicesAvailable(Unknown Source)
       at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
       at com.google.android.gms.common.api.internal.zzar.zzaib(Unknown Source)
       at com.google.android.gms.common.api.internal.zzay.run(Unknown Source)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at com.google.android.gms.internal.zzbhc.run(Unknown Source)
       at java.lang.Thread.run(Thread.java:818)

**Comment by calren** [comment]
@Albul  sorry this question wasn't addressed earlier, but given that the billing library has changed a bit since when this issue was first opened, I'm going to go ahead and close this issue. Feel free to open another issue if you find any issues with the samples in this repository. 

If you have a question regarding the billing library itself, it's best to post the question on Stackoverflow with the tag 'android-billing'.

If you are seeing issues with the billing library, you can file a bug [here](https://issuetracker.google.com/issues/new?component=311487&template=1014446) and the billing team can take a look at it.
