### ISSUE TITLE
Can not make purchase, purchase screen only show process.

### ISSUE THREAD

**Issue by snsh22** [android/play-billing-samples#124]
Hi,
I am testing In-app Billing with TrivialDrive_v2 and follow all the step from readme.md.
but it only show process view after click purchase button. what should i do ?

**Comment by snsh22** [comment]
![screenshot_2018-03-18-13-56-05](https://user-images.githubusercontent.com/17875064/37563689-2d9c3ef6-2ab5-11e8-8daf-d077370b3697.jpg)

**Comment by alexnik0888** [comment]
same issue

**Comment by calren** [comment]
Closing this issue as TrivialDrive_v2 has now been [deprecated](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440). Feel free to check out our other billing library samples [TrivialDriveKotlin](https://github.com/android/play-billing-samples/tree/master/TrivialDriveKotlin) and [ClassyTaxi](https://github.com/android/play-billing-samples/tree/master/ClassyTaxi) and file an issue if you run into any problems with the samples or want to submit a feature request. 

If you run into any issues with the Billing library itself, you can also file a report [on our official issue tracker](https://issuetracker.google.com/issues/new?component=311487&template=1014446).
