### ISSUE TITLE
verifyValidSignature when we should use it?

### ISSUE THREAD

**Issue by anonym24** [android/play-billing-samples#130]
Does this function is being called after new purchase or what? 

```
    private boolean verifyValidSignature(String signedData, String signature) {
        ...
        try {
            return Security.verifyPurchase(BASE_64_ENCODED_PUBLIC_KEY, signedData, signature);
        } catch (IOException e) {
            Log.e(TAG, "Got an exception trying to validate a purchase: " + e);
            return false;
        }
    }
```

Am I supposed to call this function here (in onActivityResult)?

from https://developer.android.com/google/play/billing/billing_integrate
```
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
   if (requestCode == REQUEST_CODE) {
      int responseCode = data.getIntExtra("RESPONSE_CODE", 0);
      String purchaseData = data.getStringExtra("INAPP_PURCHASE_DATA");
      String dataSignature = data.getStringExtra("INAPP_DATA_SIGNATURE");

      if (resultCode == RESULT_OK && verifyValidSignature(purchaseData, dataSignature)) {
         try {
            JSONObject jo = new JSONObject(purchaseData);
            String sku = jo.getString("productId");
            logDebug("You have bought the " + sku + ". Excellent choice,
               adventurer!");
          }
          catch (JSONException e) {
             logError("Failed to parse purchase data.");
             e.printStackTrace();
          }
      }
   }
}
```

`verifyValidSignature(purchaseData, dataSignature))` is this ok? `signedData == purchaseData` , `signature == dataSignature` are these equal? if so why they are called differently?

**Comment by anonym24** [comment]
and how do we check next one?

> Check the returned data signature and the orderId, and verify that the orderId is a unique value that you have not previously processed.

I understand we can get String `orderId = jo.getString("orderId");` in onActivityResult
but to check with what 

>  that you have not previously processed

Do I need to locally save all ids somewhere and check if new one equals some old? if equal then purchase is hacked?

**Comment by calren** [comment]
Closing this issue as TrivialDrive_v2 has now been [deprecated](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440). Feel free to check out our other billing library samples [TrivialDriveKotlin](https://github.com/android/play-billing-samples/tree/master/TrivialDriveKotlin) and [ClassyTaxi](https://github.com/android/play-billing-samples/tree/master/ClassyTaxi) and file an issue if you run into any problems with the samples or want to submit a feature request. 

If you run into any issues with the Billing library itself, you can also file a report [on our official issue tracker](https://issuetracker.google.com/issues/new?component=311487&template=1014446).
