### ISSUE TITLE
Can't receive PURCHASES_UPDATED broadcast

### ISSUE THREAD

**Issue by woong9105** [android/play-billing-samples#131]
This is my code. (Actucally I used [TrivialDrive](https://github.com/googlesamples/android-play-billing/tree/master/TrivialDrive) code)
`IabBroadcastReceiver mBroadcastReceiver = new IabBroadcastReceiver(MainActivity.this);
IntentFilter broadcastFilter = new IntentFilter("com.android.vending.billing.PURCHASES_UPDATED");
registerReceiver(mBroadcastReceiver, broadcastFilte)`

When I put a promo code, I could not receive any broadcast.

Is the broadcast not working? or Is my code wrong?

**Comment by calren** [comment]
Closing this issue as TrivialDrive_v2 has now been [deprecated](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440). Feel free to check out our other billing library samples [TrivialDriveKotlin](https://github.com/android/play-billing-samples/tree/master/TrivialDriveKotlin) and [ClassyTaxi](https://github.com/android/play-billing-samples/tree/master/ClassyTaxi) and file an issue if you run into any problems with the samples or want to submit a feature request. 

If you run into any issues with the Billing library itself, you can also file a report [on our official issue tracker](https://issuetracker.google.com/issues/new?component=311487&template=1014446).
