### ISSUE TITLE
java.lang.illegalStateException in IabHelper.flagStartAsync

### ISSUE THREAD

**Issue by oct-test** [android/play-billing-samples#133]
Recently, I have seen couple of crashes on my Google Developer Console with following exception:
**"java.lang.illegalStateException in labHelper.flatStartAsync"**
I am using TrivialDrive project.
How to resolve this issue? Do I need to upgrade my code?

**Comment by calren** [comment]
Closing this issue as TrivialDrive_v2 has now been [deprecated](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440). Feel free to check out our other billing library samples [TrivialDriveKotlin](https://github.com/android/play-billing-samples/tree/master/TrivialDriveKotlin) and [ClassyTaxi](https://github.com/android/play-billing-samples/tree/master/ClassyTaxi) and file an issue if you run into any problems with the samples or want to submit a feature request. 

If you run into any issues with the Billing library itself, you can also file a report [on our official issue tracker](https://issuetracker.google.com/issues/new?component=311487&template=1014446).
