### ISSUE TITLE
How to use TrivialDrive_v2

### ISSUE THREAD

**Issue by Prabha10cs** [android/play-billing-samples#136]
How to use TrivialDrive_v2
help me

**Comment by ashfaqahmed** [comment]
No comments here same issue here there is no valid activity or fragment to use incomplete example.

**Comment by calren** [comment]
Closing this issue as TrivialDrive_v2 has now been [deprecated](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440). Feel free to check out our other billing library samples [TrivialDriveKotlin](https://github.com/android/play-billing-samples/tree/master/TrivialDriveKotlin) and [ClassyTaxi](https://github.com/android/play-billing-samples/tree/master/ClassyTaxi) and file an issue if you run into any problems with the samples or want to submit a feature request. 

If you run into any issues with the Billing library itself, you can also file a report [on our official issue tracker](https://issuetracker.google.com/issues/new?component=311487&template=1014446).
