### ISSUE TITLE
A little buggy handle for consumable item

### ISSUE THREAD

**Issue by abnerlwang** [android/play-billing-samples#163]
There's a little buggy handle for consumable item.

In the function consumeAsync() of BillingManager. The purchaseToken should be removed from mTokensToBeConsumed after the consumption is successful. 

Otherwise, when the specific purchaseToken is added into BeConsumed list, it always shows "Token was already scheduled to be consumed - skipping..." and the token will never be consumed.

My suggested change is as following:
```java
        final ConsumeResponseListener onConsumeListener = new ConsumeResponseListener() {
            @Override
            public void onConsumeResponse(@BillingResponse int responseCode, String purchaseToken) {
                //remove the purchaseToken when consumption is successful
                if (responseCode == BillingResponse.OK) {
                    mTokensToBeConsumed.remove(purchaseToken);
                }
                mBillingUpdatesListener.onConsumeFinished(purchaseToken, responseCode);
            }
        };
```

**Comment by calren** [comment]
Closing this issue as TrivialDrive_v2 has now been [deprecated](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440). Feel free to check out our other billing library samples [TrivialDriveKotlin](https://github.com/android/play-billing-samples/tree/master/TrivialDriveKotlin) and [ClassyTaxi](https://github.com/android/play-billing-samples/tree/master/ClassyTaxi) and file an issue if you run into any problems with the samples or want to submit a feature request. 

If you run into any issues with the Billing library itself, you can also file a report [on our official issue tracker](https://issuetracker.google.com/issues/new?component=311487&template=1014446).
