### ISSUE TITLE
The relevant fields of the documentation could not be found

### ISSUE THREAD

**Issue by Mollylian** [android/play-billing-samples#164]
such as, The contents of the JSON response vary could not  found expiryTimeMillis and paymentState.Access to Play Billing Library 1.2 how to determine the user's failure to renew the current account retention period.

**Comment by calren** [comment]
@Mollylian I'm a bit unclear on the question you're asking about, but feel free to check out our documentation for [products](https://developers.google.com/android-publisher/api-ref/purchases/products) and [subscriptions](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions).

It's also worth noting that the newest [Billing Library](https://developer.android.com/google/play/billing/billing_library_overview) is now on version 2.0, and we highly recommend developers use this new version.

I'll close this issue for now, but if you have any other questions / issues regarding the sample app, feel free to reopen the issue or file another one.
