### ISSUE TITLE
SkuDetails getSubscriptionPeriod

### ISSUE THREAD

**Issue by plugie** [android/play-billing-samples#168]
In https://developer.android.com/reference/com/android/billingclient/api/SkuDetails we can find getSubscriptionPeriod function.

But in IABHelper, I can't find itu.

Can I just add getSubscriptionPeriod like below code ? Or any other solution ?

```
public SkuDetails(String itemType, String jsonSkuDetails) throws JSONException {
        mItemType = itemType;
        mJson = jsonSkuDetails;
        JSONObject o = new JSONObject(mJson);
        mSku = o.optString("productId");
        mType = o.optString("type");
        mPrice = o.optString("price");
        mPriceAmountMicros = o.optLong("price_amount_micros");
        mPriceCurrencyCode = o.optString("price_currency_code");
        mTitle = o.optString("title");
        mDescription = o.optString("description");
        mSubscriptionPeriod = o.optString("subscription_period");
    }

public String getSubscriptionPeriod () { return mSubscriptionPeriod ; }
```

**Comment by calren** [comment]
Closing this issue as TrivialDrive_v2 has now been [deprecated](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440). Feel free to check out our other billing library samples [TrivialDriveKotlin](https://github.com/android/play-billing-samples/tree/master/TrivialDriveKotlin) and [ClassyTaxi](https://github.com/android/play-billing-samples/tree/master/ClassyTaxi) and file an issue if you run into any problems with the samples or want to submit a feature request. 

If you run into any issues with the Billing library itself, you can also file a report [on our official issue tracker](https://issuetracker.google.com/issues/new?component=311487&template=1014446).
