### ISSUE TITLE
TrivialDrive_v2 memory leak?

### ISSUE THREAD

**Issue by GreenRollingHills** [android/play-billing-samples#174]
Hello,

I launched the app on the Pixel XL API 28 emulator.  I then used Android Studio’s profiler to check for any memory leaks.  After one rotation I found this : 

TrivialDriveActivity : 2 allocations, 0 deallocations, 2 total count.
BillingManager : 2 allocations, 0 deallocations, 2 total count.
BillingClientImpl : 2 allocations, 0 deallocations, 2 total count.

plus more …

Is there a leak in the TrivialDrive_v2 app?

Thanks,

**Comment by calren** [comment]
Closing this issue as TrivialDrive_v2 has now been [deprecated](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440). Feel free to check out our other billing library samples [TrivialDriveKotlin](https://github.com/android/play-billing-samples/tree/master/TrivialDriveKotlin) and [ClassyTaxi](https://github.com/android/play-billing-samples/tree/master/ClassyTaxi) and file an issue if you run into any problems with the samples or want to submit a feature request. 

If you run into any issues with the Billing library itself, you can also file a report [on our official issue tracker](https://issuetracker.google.com/issues/new?component=311487&template=1014446).
