### ISSUE TITLE
How to setReplaceSkusProrationMode in getBuyIntentToReplaceSkus?

### ISSUE THREAD

**Issue by wangdaliu** [android/play-billing-samples#182]
i am using getBuyIntentToReplaceSkus to update my subscription.
buyIntentBundle = mService.getBuyIntentToReplaceSkus(5, 
                   mContext.getPackageName(),oldSkus, sku, itemType, extraData);

i want to add proration mode while updating my sku. I have seen a method here https://developer.android.com/google/play/billing/billing_subscriptions#Allow-upgrade But i don't know how use this with getBuyIntentToReplaceSkus. Here is the code that i have seen on that link.

BillingFlowParams flowParams = BillingFlowParams.newBuilder()
    .setSku(skuId)
    .setType(billingType)
    .setOldSku(oldSku)
    .setReplaceSkusProrationMode(replaceSkusProrationMode)
    .build()
int responseCode = mBillingClient.launchBillingFlow(activity, flowParams);

**Comment by isaidamier** [comment]
If you choose to set a ProrationMode you have to use one of the pre-existing constants of `BillingFlowParams.ProrationMode.__` as in the pattern `.setOldSku(oldSku).setReplaceSkusProrationMode(BillingFlowParams.ProrationMode.IMMEDIATE_WITHOUT_PRORATION)`

**Comment by calren** [comment]
@wangdaliu Hopefully Isai has answered your question! I'll go ahead and close this issue now
