### ISSUE TITLE
Is this a complete app ?

### ISSUE THREAD

**Issue by Boardstein** [android/play-billing-samples#184]
Im a Big noob in developing apps, i want to build an app for inapp purchases only. Is this a complete template i can use or what is this?

**Comment by isaidamier** [comment]
You might be able to use the [TrivialDriveKotlin]( https://github.com/googlesamples/android-play-billing/tree/master/TrivialDriveKotlin) sample for your needs.

**Comment by calren** [comment]
Hey @Boardstein , this repo contains examples of how to implement subscriptions (ClassyTaxi) and one-time purchases (TrivialDriveKotlin). It's not exactly a template that you can plug and use, but more of a guideline for you to see how these features can be implemented. Thanks!
