### ISSUE TITLE
What to do if Not acknowledged before the deadline?

### ISSUE THREAD

**Issue by vitovalov** [android/play-billing-samples#195]
While testing **TrivialDriveKotlin** using testing account I got upon calling `playStoreBillingClient.acknowledgePurchase`:

_"The purchase was not acknowledged before the deadline."_

At this point the purchase stays in purchases table and isn't entitled to the user. 

What needs to be changed inside TrivialDriveKotlin `BillingRepository` to handle this case ?

**Comment by calren** [comment]
Hey @vitovalov , you can check out the process for acknowledging purchases here : https://developer.android.com/google/play/billing/billing_library_overview#acknowledge

Thanks!
