### ISSUE TITLE
Serverless billing integration - subscription verification throw various devices

### ISSUE THREAD

**Issue by PFittech** [android/play-billing-samples#202]
Is it possible to verify whether the user have subscription throw various devices **serverless** if user have the same account? 

People report that they bought a subscription on mobile phone but on a tablet which has the same account is subscription not purchased. Even though they have the same account... they do not have a subscription.. I'd like to solve it without a server.

My integration: 
[premium.txt](https://github.com/googlesamples/android-play-billing/files/3293887/premium.txt)

I follow example: https://github.com/googlesamples/android-play-billing/blob/master/TrivialDriveKotlin/app/src/main/java/com/kotlin/trivialdrive/billingrepo/BillingRepository.kt

**Comment by PFittech** [comment]
@cartland or someone ... some feedback? Did I ask stupid thing?

**Comment by isaidamier** [comment]
Have you tried testing this yourself? Two different devices, same account. Buy on one device and check if you get a non-empty list on the other device for

`result = playStoreBillingClient.queryPurchases(BillingClient.SkuType.SUBS)` ?

**Comment by isaidamier** [comment]
I am aware of the issue and will update the sample to address this rare case. In the meantime please use the snippet I provide on [StackOverflow](https://stackoverflow.com/questions/57367238/google-play-billing-method-querypurchasehistoryasync-not-getting-all-purchases/57529322#57529322). You may also find [this answer](https://stackoverflow.com/questions/57109263/is-there-any-way-to-validate-a-purchase-against-google-play-not-the-cache-from?noredirect=1&lq=1) helpful.

**Comment by calren** [comment]
Hey @PFittech , hopefully you had a chance to check out Isai's suggestion above! In the meantime, I'm going to go ahead and close this issue since it's not a problem specific to the samples.
