### ISSUE TITLE
Sample code doesn't handle null lists

### ISSUE THREAD

**Issue by mduffor** [android/play-billing-samples#216]
We ran into multiple bugs in our Google Billing v2 implementation that didn't show up until we shipped into the wild, all because we followed the sample code too closely (both in GitHub and in Google's implementation tutorials).

For example, in BillingManager.java in queryPurchases(), there is the line:
    purchasesResult.getPurchasesList().addAll(subscriptionResult.getPurchasesList());

This line can fail because getPurchasesList() can return a null on some devices rather than an empty list.  Likewise in onQueryPurchasesFinished() when it calls onPurchasesUpdated, it could pass an empty list from the call to result.getPurchasesList().  In queryPurchases the log call to  "Querying subscriptions result code: " can also get a null exception when it tries to get size() on a  null list.

There is also the issue that although the Google Billing v2 tutorials link to this GitHub repository (https://developer.android.com/google/play/billing/billing_library_overview), the sample hasn't been updated to v2 yet.

Cheers!

**Comment by isaidamier** [comment]
Deepest apologies for the issues you encounter. Might you be able to follow the TrivialDriveKotlin sample in the meantime?

**Comment by calren** [comment]
@mduffor Thanks for letting us know about this issue! We definitely should have handled these potential null results better in our sample app. In an effort to consolidate the effort around sample apps, we've decided to deprecate the existing Java samples for now, so I'll be closing this issue since TrivialDriveV2 is now deprecated.
