### ISSUE TITLE
Price change with an auto renewable subscription

### ISSUE THREAD

**Issue by Vexole** [android/play-billing-samples#234]
There is a need to retain the previous subscription price for old users for a certain custom defined period of time after the change of subscription price. Is there any way to handle situations like this? We have maintained user purchase history in our local DB.

**Comment by calren** [comment]
@Vexole The best approach would be to create a new SKU to differentiate between old users and new users and to stop offering the old SKU with the old subscription price. 

Since this is a general billing library question unrelated to the samples, I'll be closing this issue
