### ISSUE TITLE
Google Play In-app Billing API version is less than 3

### ISSUE THREAD

**Issue by mryaodong** [android/play-billing-samples#235]

**Comment by xiaoluqiaoba** [comment]
Hello, have you solved this problem? I also encountered the same problem

**Comment by isaidamier** [comment]
Would you please clarify? If you are commenting on another question that has been closed, please simply reopen that question with greater details. Thanks

**Comment by yaugenka** [comment]
I'm facing the same issue as well. Using billing:2.0.3

**Comment by ElegyD** [comment]
Are you logged in to Google Play?
If not, login with your account, then the error should go away. See [here](https://stackoverflow.com/a/58798150/6808319)

**Comment by calren** [comment]
@mryaodong @xiaoluqiaoba 

Google Play Console displays this warning if we detected that your app was still using version 1 or version 2 of the Google Play Developer API endpoints. The message is based on all calls to the API in the last seven days and is refreshed daily. If you see this message, it means calls to the Publishing API version 1 or 2 are referencing your app.

You can check out [this blog post](https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html) for more details on how to update your app to use the latest version of the Google Play Developer API.

**Comment by dddddl** [comment]
I am using the implementation 'com.android.billingclient: billing: 2.0.3' version of Google payment api. It works fine on Google Play in the US, but when I switch to Google Play in Hong Kong, my app reports the Google Play In-app Billing API version is less than 3 error. I do n’t know how to solve it.

**Comment by AlexeyErmolovich311** [comment]
Hello @calren, I have the same problem like @dddddl. Could you explain how to solve it?
