### ISSUE TITLE
How exactly should we handle pending transactions?

### ISSUE THREAD

**Issue by bellissimo** [android/play-billing-samples#236]
Since Billing 2.0 we are required to call 'enablePendingPurchases' on startup. However I can't see anything in the documentation or examples as to how exactly we are supposed to handle these pending transactions.

The documentation hints that for a pending transaction: "Here you can confirm to the user that they've started the pending purchase, and to complete it, they should follow instructions that are given to them." So how does this work in practice. For example is it that:

1)  They automatically receive further UI from Google (after they close the alert from the developer?) within the app prompting them to 'complete' the transaction in some way.
2)  We tell them to come back a bit later once the transaction completes automatically and we can acknowledge it the next time the app is resumed
3) Some other process I have not considered

Secondly, will pending transactions still need acknowledgement within three days? I would guess not, since refunds not possible for such purchases...

**Comment by Wensibob** [comment]
Hey,have you solved this question?

**Comment by calren** [comment]
You can check out an example of how to handle pending transactions in [TrivialDriveKotlin](https://github.com/android/play-billing-samples/blob/cc8b18916ba76f8cf9ec5d12b4da6ca0e74772a6/TrivialDriveKotlin/app/src/main/java/com/kotlin/trivialdrive/billingrepo/BillingRepository.kt#L597)

For more context around pending purchases, check out this talk from the Android Developer Summit: https://youtu.be/L2aiHRD6Pfk

**Comment by AlexVPerl** [comment]
> You can check out an example of how to handle pending transactions in [TrivialDriveKotlin](https://github.com/android/play-billing-samples/blob/cc8b18916ba76f8cf9ec5d12b4da6ca0e74772a6/TrivialDriveKotlin/app/src/main/java/com/kotlin/trivialdrive/billingrepo/BillingRepository.kt#L597)
> 
> For more context around pending purchases, check out this talk from the Android Developer Summit: https://youtu.be/L2aiHRD6Pfk

Sample project does not give any new info besides what's already in the documentation and neither does the video. 

Sample project contains the following - not very useful:
```
Log.d(LOG_TAG, "Received a pending purchase of SKU: ${purchase.sku}")
// handle pending purchases, e.g. confirm with users about the pending
//purchases, prompt them to complete it, etc.
```

The 20 min Summit video just has 1 sentence on this, just that users expect to see some sort of a message - again not much very helpful either.

Some practical / real world examples of handling PENDING state would be helpful.
