### ISSUE TITLE
TrivialDrive_v2 has not been updated to Billing Library 2

### ISSUE THREAD

**Issue by hrydgard** [android/play-billing-samples#238]
Copying the BillingManager.java and friends into a new project, they fail to compile due to several API differences such as BillingResponse -> BillingResponseCode, and setSku.

Do you really expect everyone to switch to Kotlin?

**Comment by holoitsme** [comment]
I think it's shame that Google does not provide us with some updated documentation, codelabs and examples. I mean, a huge part of our users money goes directly to their pocket, it's their interest to make things easier for developers.

Please someone at Google, help us.

**Comment by calren** [comment]
Thanks for the feedback all. TrvialDrive_v2 has been deprecated now since it wasn't using the latest billing library, so I'll go ahead and close this issue. But if you feel like the addition of a Java sample would be helpful, feel free to open a separate issue.

**Comment by hrydgard** [comment]
For visibility: Opened #260 to request a replacement sample.
