### ISSUE TITLE
We've detected that your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available

### ISSUE THREAD

**Issue by Ananthusubramanian** [android/play-billing-samples#244]
https://github.com/android/play-billing-samples/tree/master/ClassyTaxi/firebase is using V2 of google api it should be updated

**Comment by calren** [comment]
[Fixed](https://github.com/android/play-billing-samples/commit/912d9562b6df41895588f1560905b4ca9e8ee7ee) by @Ananthusubramanian
