### ISSUE TITLE
[TrivialDriveKotlin] Small error in getOldSku()

### ISSUE THREAD

**Issue by ElegyD** [android/play-billing-samples#247]
Shouldn't this return GameSku.GOLD_MONTHLY ?

https://github.com/android/play-billing-samples/blob/b0ca34426ca7bddfbcb0557e195ea69898320440/TrivialDriveKotlin/app/src/main/java/com/kotlin/trivialdrive/billingrepo/BillingRepository.kt#L795

**Comment by calren** [comment]
@ElegyD  Yes that would make a lot more sense! Feel free to open a PR for this issue
