### ISSUE TITLE
ClassyTaxi : Changing Google Play Developer Api to v3

### ISSUE THREAD

**Issue by eisdrachl** [android/play-billing-samples#250]
Hello, 

I'm having trouble deploying to firebase for ClassyTaxi. I have all set like the repository here, but I always get the following error after trying "firebase deploy":

Error occurred while parsing your function triggers.
Error: Unable to load endpoint androidpublisher("v3"): endpoint is not a constructor

Can some one help me with this? I really googled a lot, but I couldn't find a fix. Thanks in advance!

**Comment by calren** [comment]
Hey @eisdrachl , thanks for reporting about this! We did make a change around this recently, and it's very possible something was not updated correctly. I'll be looking into this today. In the meantime, you can locally change the google developer play version back to 2 (basically reverting [this commit](https://github.com/android/play-billing-samples/commit/912d9562b6df41895588f1560905b4ca9e8ee7ee) and that should get things working again.

Will keep you updated on what I find
