### ISSUE TITLE
DEVELOPER_ERROR and "Purchase not found for the given token" when acknowledge subscription product

### ISSUE THREAD

**Issue by lyw-94** [android/play-billing-samples#251]
Recently I found that there are some DEVELOPER_ERROR error in our online app, and the debug message is **"Purchase not found for the given token"**, here are my code
`
AcknowledgePurchaseParams params =
AcknowledgePurchaseParams.newBuilder()
.setPurchaseToken(purchase.getPurchaseToken())
.setDeveloperPayload(developerPayload)
.build();

mBillingClient.acknowledgePurchase(params, listener);
`
And the purchase object is return from onPurchasesUpdated method, also i checked the user's purchaseToken , which is the same with i found in google play order management background.

so, what is the root cause of this problem? the order will refund in 3 days if we not acknowledge it, i'm so confused.

**Comment by lyw-94** [comment]
need help ^_^

**Comment by lyw-94** [comment]
🙂🙂🙂

**Comment by joyceHong0524** [comment]
@lyw-94 Did you solve this problem and how?

**Comment by lyw-94** [comment]
@joyceHong0524  yes, just invoke Purchase.isAcknowledged() method to check if the purchase need to acknowledge
