### ISSUE TITLE
not getting IAP pop up

### ISSUE THREAD

**Issue by clickdigitalinteractive** [android/play-billing-samples#257]
I installed classy taxi and back end server, I can log in with google account or email on both app and web app but if I click 'basic' or 'premium' nothing pop's up asking me to purchase? I've set the two iap subscription items correctly. I don't get an error or anything...

**Comment by AliAzaz** [comment]
device on which you are working?

**Comment by calren** [comment]
Hey @clickdigitalinteractive , it takes a while (up to a couple of days) for Google Play store to process your app when you first upload it. If your app hasn't been successfully uploaded to Google Play store, you won't be able to make the purchases just yet.

Hopefully you were able to try again a few days later and see a more successful result! Feel free to open another issue if you're still not seeing the IAP pop up, but I'll go ahead and close this one for now.
