### ISSUE TITLE
Replacement for TrivialDrive_v2 sample needed (Java sample)

### ISSUE THREAD

**Issue by hrydgard** [android/play-billing-samples#260]
The Java sample TrivialDrive_v2 was never updated to the new API, as mentioned in #238.

I'm maintaining an older application where I have absolutely no desire to convert to Kotlin. I want to update it to the latest Play billing API, but the lack of a working Java sample makes that task very arduous.

It's ridiculous that such a high profile API, critical for so many developers, does not have a working official Java sample. Please fix this.

**Comment by calren** [comment]
Thanks @hrydgard for opening this issue! For other developers who see this, feel free to give a 'thumbs up' reaction if you have similar thoughts.

**Comment by techvasanth** [comment]
Java sample very much required till Kotlin/Dart/Flutter  community becomes stable.

**Comment by fabiofrack** [comment]
Java sample with all the best practices could be useful.

**Comment by LordByron1788** [comment]
> Thanks @hrydgard for opening this issue! For other developers who see this, feel free to give a 'thumbs up' reaction if you have similar thoughts.

Hi, 
Please can you advise if you are likely to produce a Java sample for this new API? Billing is a business critical process, and not everybody is able to migrate to Kotlin.
Thanks

**Comment by calren** [comment]
Hey all, just wanted to give an update that we are actively working on a Java sample that demonstrates using the Play Billing Library and a basic version of the app should be ready before I/O 2020 (mid May), but hopefully much sooner than that! Thanks for all the feedback to let us know what the community needs, it really helps!

**Comment by agGitHub** [comment]
Urgent need for a Trivial Drive java version ! Thanks !

**Comment by calren** [comment]
Hey all, quick update that we just pushed [ClassyTaxiJava](https://github.com/android/play-billing-samples/tree/master/ClassyTaxiJava) , which is the Java equivalent of ClassyTaxiKotlin, so I'll be closing out this issue.

Currently ClassyTaxiJava only supports subscription based features, but we're looking to add one-time purchases support as well. If there are any other features you'd like to see in ClassyTaxi, feel free to file an issue!

**Comment by LordByron1788** [comment]
It is great there is a now a Java version of Classy Taxi. But the original point of this issue was to create a Java sample of the Trivial Drive app. Trivial drive app is server-less billing. What was the point in closing out this issue when the work is not complete? Also, of course examples of one-time purchases are required as well as subscription features. This is very disappointing to see this Issue closed with haste with the work not being done. Creating another issue is effectively recreating this same issue again.

**Comment by calren** [comment]
@LordByron1788 We highly recommend developers to NOT implement server-less billing, which is one of the reasons we deprecated TrivialDrive_v2. You can read more about best practices [here](https://developer.android.com/google/play/billing/billing_best_practices).

For one time purchases, there's an open issue [here](https://github.com/android/play-billing-samples/issues/276) that's being actively worked on.

**Comment by LordByron1788** [comment]
The official documentation clearly states:
*"If you cannot use a server, however, it's still possible to validate these details within your app on a device."*
So therefore if it is possible then there should be examples of it. Also, that hasn't stopped you releasing an official Kotlin version of the Trivial Drive app which is also server-less.

**Comment by agGitHub** [comment]
Yes, we need a server less version, as it is proposed for the Kotlin version. Thanks !

**Comment by calren** [comment]
It seems like there is some interest for an example that integrates Play Billing without a server. I created this [issue](https://github.com/android/play-billing-samples/issues/278) to help track this. If you would like to see such an example app, feel free to leave a comment on the issue itself.
