### ISSUE TITLE
Classy Taxi: java.lang.IllegalArgumentException: Given String is empty or null

### ISSUE THREAD

**Issue by dev3forfun** [android/play-billing-samples#264]
Hello.

I would like to run the Classy Taxi app before uploading to the Play Console Store. I've already followed the instruction up to downloading the google-services.json file and putting it into the app project, but for some reason, I keep running into "java.lang.IllegalArgumentException: Given String is empty or null" message. I've looked online, and verified that the "current_key" in "api_key" is not empty or null. 

Could you please help me on this?

Thank you.

**Comment by calren** [comment]
@dev3forfun When are you running into this error message? Is it when you're building the app? Or when you click on a specific button?

**Comment by dev3forfun** [comment]
It was at the start of running the app, without showing anything on screen. The app has successfully build and install.

**Comment by calren** [comment]
@dev3forfun Make sure you followed the steps to[ set up Firebase for your app](https://github.com/android/play-billing-samples/tree/master/ClassyTaxiAppKotlin#firebase-project-setup) and that you replaced the google-services.json in the `debug` directory.
