### ISSUE TITLE
TrivialDriveKotlin BillingRepository fragile public functions

### ISSUE THREAD

**Issue by cypherdare** [android/play-billing-samples#267]
Several public functions of BillingRepository access the `lateinit` property `playStoreBillingClient`. However, it is optional for this property to be instantiated because `startDataSourceConnections()` is optional to call. 

BillingViewModel actually calls through to one of these functions (`queryPurchasesAsync()`) with its own public function `queryPurchases()`.

**Comment by DAGalpin** [comment]
The rewrite starts the connection to Google Play automatically.
