### ISSUE TITLE
Pending order more than 90%

### ISSUE THREAD

**Issue by RuijiePan** [android/play-billing-samples#268]
I have a app with subscriotion.But later 3 days free, more than 90% user receiver a new order.But the order purchase status is Purchase.PurchaseState.PENDING.May I can do anything when user order status is pending? And I want to know why their order status is pending.Thanks.
In demo, I see "handle pending purchases, e.g. confirm with users about the pending purchases, prompt them to complete it, etc.", and how to handle it.

**Comment by dddddl** [comment]
老哥 你是如何处理的呢
