### ISSUE TITLE
Play Billing is the worst nightmare I have ever had

### ISSUE THREAD

**Issue by n0m0r3pa1n** [android/play-billing-samples#270]
The API of Google Play Billing library is shit. You basically need 2 public methods available in this library:
 - Get the list of purchases
 - Launch the billing flow

Then everything can be done like checks whether the purchase is paid or pending, or whether there was any problem with something on the developer side. 

Why is all of this code pollution and all those shitty checks? There are so many wrappers available here around this library to make it simpler to understand and yet, you can not put a rose on the shit and say it is beautiful.

Then, this behavior of the library. Something is null, something is not null, there are 12 cases that devs need to handle in case something goes wrong:
` @Retention(RetentionPolicy.SOURCE)
    public @interface BillingResponseCode {
        int SERVICE_TIMEOUT = -3;
        int FEATURE_NOT_SUPPORTED = -2;
        int SERVICE_DISCONNECTED = -1;
        int OK = 0;
        int USER_CANCELED = 1;
        int SERVICE_UNAVAILABLE = 2;
        int BILLING_UNAVAILABLE = 3;
        int ITEM_UNAVAILABLE = 4;
        int DEVELOPER_ERROR = 5;
        int ERROR = 6;
        int ITEM_ALREADY_OWNED = 7;
        int ITEM_NOT_OWNED = 8;
    }

    @Retention(RetentionPolicy.SOURCE)
    public @interface FeatureType {
        String SUBSCRIPTIONS = "subscriptions";
        String SUBSCRIPTIONS_UPDATE = "subscriptionsUpdate";
        String IN_APP_ITEMS_ON_VR = "inAppItemsOnVr";
        String SUBSCRIPTIONS_ON_VR = "subscriptionsOnVr";
        String PRICE_CHANGE_CONFIRMATION = "priceChangeConfirmation";
    }`

Are you freaking kidding me, right?

Other thing is that you have different names. In the library you created, you call the MANAGED_PRODUCTS -> IN_APP_PURCHASES. Like why do you even have different names for the same thing? And WTF does OnVr mean?

And yet, in your website: https://developer.android.com/distribute/play-billing it says the following?
<img width="1244" alt="Screenshot 2020-01-20 at 13 18 42" src="https://user-images.githubusercontent.com/2341201/72722621-7226f180-3b87-11ea-80a9-2579d855289b.png">

Easily integrate!? What to easily integrate? The shit with the rose on it?

P.S.
I don't even want to write about testing ..

**Comment by gitwat** [comment]
Oh...  understand your pain. Added it to favorites. Sick of it too!

**Comment by gitwat** [comment]
Deep deep breath and continuing )

**Comment by lauriolasw** [comment]
Totally Agree

**Comment by LordByron1788** [comment]
Yes, it is complete garbage.

Perhaps, you should add your thoughts about it here:  #321

New developers getting into Android need to be warned about it.

The amount of hours, days,weeks, months you will waste on it is ridiculous.

It is just not worth it.

**Comment by brendanw** [comment]
Just updating to v6 and in the pursuit of catharsis was looking for a post like this...thank you. keeping google play working w/ library updates continues to take way more time than is reasonable.
