### ISSUE TITLE
Trivial Drive Kotlin Screen Shots Not Found

### ISSUE THREAD

**Issue by dakkad** [android/play-billing-samples#273]
https://github.com/android/play-billing-samples/tree/master/TrivialDriveKotlin#screenshots

On the Trivial Drive Kotlin sample page the screenshots for the project are not found.

**Comment by calren** [comment]
Thanks for reporting! It must've gotten lost during one of the recent refactorings. We'll be sure to add it back.

**Comment by DAGalpin** [comment]
Fixed with update.
