### ISSUE TITLE
Replacement for TrivialDrive_v2 sample needed (Java sample)

### ISSUE THREAD

**Issue by LordByron1788** [android/play-billing-samples#277]
As mentioned in #260, we need a Java sample of the TrivialDrive_V2 app, that uses the latest Billing API.

This version needs to include examples of all supported in-app products types (Subscriptions, Consumables, Non-consumables etc..)

Currently there is only a Kotlin version that demonstrates server-less billing. Android documentation clearly states:
_"If you cannot use a server, however, it's still possible to validate these details within your app on a device."_

Please add Java sample that also demonstrates this.

Thanks,

**Comment by calren** [comment]
Since we strongly recommend developers to NOT use server-less billing, we will not be publishing a sample that demonstrates that.

Android documentation is being updated to reiterate our recommendation that developers not use server-less billing. 

We are working on supporting consumables and nonconsumables in ClassyTaxiJava and ClassyTaxiKotlin

**Comment by LordByron1788** [comment]
I would like to officially make a complaint about the way you have handled this issue and completely misled us in terms of your intentions with the Trivial Drive app (an example of a server-less billing app).

You should have clearly communicated 3 months ago, you were not going to replace this. Prior to today, you gave every indication that Trivial Drive was getting a Java sample with the latest billing API. So we waited. There were no requests for ClassyTaxi to be updated on issue #260.

Switching to using servers, is not a trivial matter and has a huge impact for developers and businesses. These decisions affect people's lives. Is the Kotlin version of Trivial Drive now also going to be removed !?

Just closing Github issues and ignoring community feedback is very disappointing and somewhat shocking to witness on an official Google repo. It serves no purpose other than to create resentment and distrust towards these samples. It also demonstrates that Google does not take developer feedback seriously. I will be sharing my experience of this with others.
