### ISSUE TITLE
Create Java sample to showcase implementing Play Billing without a server

### ISSUE THREAD

**Issue by calren** [android/play-billing-samples#278]
Currently we have the following samples:
- [ClassyTaxiJava](https://github.com/android/play-billing-samples/tree/master/ClassyTaxiJava) / [ClassyTaxiKotlin](https://github.com/android/play-billing-samples/tree/master/ClassyTaxiAppKotlin)
- [TrivialDriveKotlin](https://github.com/android/play-billing-samples/tree/master/TrivialDriveKotlin)

ClassyTaxi showcases all the best practices we recommend when working with Play Billing, including having a server to validate purchases. 

TrivialDriveKotlin, on the other hand, is an example of integrating Play Billing without a server. Based on some feedback, it seems like some developers would like to see a Java sample that showcases Play Billing without a server implementation. While we highly recommend you include a server solution with your Play Billing features, we understand that not all developers have the necessary bandwidth or need for a server solution.

This issue is to track feedback about what people would like to see in a potential Java sample that integrates Play Billing without a server. Requests could be something like:
- I would like to see how to use the latest version of the Play Billing library if my app doesn't have a server
- I would like to see how to best architect an app when integrating the Play Billing library
- I would like to see how to implement {x} feature with the Play Billing library.

If you would simply like to see a Java version of TrivialDriveKotlin, you can also react to this issue with a 'thumbs up' emoji.

**Comment by DontTrustMicrosoft-MicrosoftIsAsshole** [comment]
2 years later nothing. I wonder how much money Google lost on people that just said f*** it I'm not playing this "game" anymore, stopped coding all together and started a farm somewhere...The idea is growing on me more and more. Maybe that's what Google wants. Obviously it was a political not a logical change  🐄.🐄.🐄

**Comment by LordByron1788** [comment]
> 2 years later nothing. I wonder how much money Google lost on people that just said f*** it I'm not playing this "game" anymore, stopped coding all together and started a farm somewhere...The idea is growing on me more and more. Maybe that's what Google wants. Obviously it was a political not a logical change 🐄.🐄.🐄

Billing on Android is horrendous, and so is this repo. It has gone downhill completely this year. No progress is being made on anything, it is beyond a joke. Google stopped caring a long time ago. I guess free lunches and ping pong is all they do over at Google HQ.

**Comment by snoutholder** [comment]
I use serverless purchases with java and now Google Play is forcing me to update my purchase library, yet not providing me with a simple path with a working sample. I'm just trying to maintain my code. Where is the sample for trivialdrive java? I don't want to use subscriptions, so the existing java one is not adequate. And I don't want to hack something together using the bits and pieces provided by Google's migration.

**Comment by LordByron1788** [comment]
> I use serverless purchases with java and now Google Play is forcing me to update my purchase library, yet not providing me with a simple path with a working sample. I'm just trying to maintain my code. Where is the sample for trivialdrive java? I don't want to use subscriptions, so the existing java one is not adequate. And I don't want to hack something together using the bits and pieces provided by Google's migration.

It's ridiculous, over 1 year ago this was logged, with 35 thumbs up over 2 issues, and still nothing.

If Google can't even deliver a sample in 1 year, then that should tell you everything you need to know about how good the Billing Library is. Not even Google developers can work with it. Either that or it's the developers that are at fault.

All we get are a couple of useless Medium articles on Billing. 

If the original problem in #260 had been understood from the outset, then this issue #278 wouldn't have been raised.

**Comment by DAGalpin** [comment]
TrivialDriveJava implemented, along with an update to TrivialDriveKotlin.
