### ISSUE TITLE
ClassyTaxiServer deployment fails with current project setup and instructions

### ISSUE THREAD

**Issue by calren** [android/play-billing-samples#288]
```
[17:27:35] xiaodao:ClassyTaxiServer git:(master*) $ firebase deploy

=== Deploying to 'social-app-android-852fd'...

i  deploying functions, hosting
Running command: npm --prefix "$RESOURCE_DIR" run lint
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/xiaodao/Projects/android/play-billing-samples/ClassyTaxiServer/server/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/xiaodao/Projects/android/play-billing-samples/ClassyTaxiServer/server/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiaodao/.npm/_logs/2020-03-23T09_27_41_411Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code254
```

Notes:
In firebase.json, https://github.com/android/play-billing-samples/blob/master/ClassyTaxiServer/firebase.json
There are no 'server' or 'web' directory, firebase cann't deploy functions and hosting with these folder.

**Comment by vafaminato** [comment]
Hello. Did anyone find any answer for this error? I still get deployment error. I noticed after initiating `firebase deploy` command, the "server" folder is made inside the project folder. What should we do? I tried to put the `package.json` file from the project into the server folder. Still no success. please fix this. We need a fix for it.

**Comment by calren** [comment]
Hey @vafaminato , you can checkout the branch in [this pull request](https://github.com/android/play-billing-samples/issues/288) for the fix.

**Comment by vafaminato** [comment]
Hi Caren. I finally deployed firebase. But please give more explanations.
Because we figured this out in stackoverflow. We have to put everything
inside "server" folder +

for windows we have to use npm --prefix \"%RESOURCE_DIR%\" run lint" and
"npm --prefix \"%RESOURCE_DIR%\" run build". Otherwise we get the error.

bests
sajad.

**Comment by Kossi-Francois** [comment]
@vafaminato Hi, I would like to know if you have recently tried to deploy the backend  server and if it works?
thank you in advance.
