### ISSUE TITLE
Possible fraud using credentials in an unlimited number of devices

### ISSUE THREAD

**Issue by ishomam** [android/play-billing-samples#299]
Hello guys,

I'm applying your billing example to my app. However, I was thinking that in this verification model the user is able to use his credentials in an unlimited number of devices, right?

Doesn't this allow fraud if the user published or sold his credentials to a big number of people so all of them have access to the premium content. Or am I just misunderstanding something?
Shouldn't this be restricted somehow?

Thanks

**Comment by calren** [comment]
Hey @ishomam ! Just for clarification, are you referring to associating purchases to a user's Google Play account? Or associating purchases to a signed in user outside of Google Play? 

In either case, it may be hard to prevent fraud if we want to allow users to still be able to access the content they purchased if they were on another device. Taking into account that most users may have more than one device, and that most mobile users get a new device on average every 2 years, it could be a negative user experience to limit purchases to one device, which is mostly why we went with our approach. 

I'm going to close out this issue and it's not something we plan on addressing through these samples, but feel free to keep commenting regarding this discussion!

**Comment by ishomam** [comment]
Hi Caren,

Thanks for the clarification. I was talking mainly about email logins (not
google account logins). I think if it would be possible to allow user to
login into for example 4 devices at the same time and each new login will
then cause a log out from the oldest device, then I think this would be
fair and more secure against fraud (user can give away the email and
password he used to hundreds of people so all will have access to the
premium content)

Best regards,

Homam
