### ISSUE TITLE
In-app purchases (managed products) with backend server?

### ISSUE THREAD

**Issue by vafaminato** [android/play-billing-samples#301]
Is would be great to complete this code and add the in-app purchases for consumable and on-time-purchase products with backend server implementation. I want to know your opinion.

**Comment by calren** [comment]
Hey @vafaminato , would https://github.com/android/play-billing-samples/issues/276 describe what you're thinking about? It's something that's been on our backlog, but haven't gotten to yet. If so, maybe we can close this one as a duplicate?
