### ISSUE TITLE
ClassytaxiKotlin: No matching client found for package name

### ISSUE THREAD

**Issue by vafaminato** [android/play-billing-samples#304]
The app does not run. I searched and seems it should be related to the google-services.json package name difference with the app package name. But it is not. 

```
What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name
```

Removing the `apply plugin: 'com.google.gms.google-services' ` let the app run but there is another issue.

**Comment by vafaminato** [comment]
Does anyone have these issues or is it just me???

**Comment by calren** [comment]
Hm, I'm unable to reproduce this error. I was able to check out the project from Github, set it up as a Firebase project, replace the google-services.json file with the one I downloaded after creating a new Firebase project, and run ClassyTaxi successfully. 

Sorry this was filed a while ago and we didn't see it until now. If you still remember the steps to reproduce this, do you mind listing it here so we can try and reproduce this problem?
