### ISSUE TITLE
TrivialDriveKotlin doesn't update the basic subscription status

### ISSUE THREAD

**Issue by vafaminato** [android/play-billing-samples#305]
1. Install the app --> OK
2. Purchase the basic subscription --> OK
3. confirm the purchase inside the google play console as charged and play store app --> OK
4. cancel the basic subscription from play store app --> OK
5.  confirm the cancellation after 7 minutes (not listed as subscriptions anymore in google play and no more charged inside google play console) --> OK
6. open the app. BUT still the monthly subscription button is inactive (as if you already have basic subscription) --> X
7. Waiting a bit more (like hours), or restarting the phone, cleaning play store cache --> still the same 
8. Reinstall the app --> Now it works again and the basic subscription button is active

**Comment by jaksab** [comment]
I have the same problem

**Comment by vafaminato** [comment]
@jaksab As official google doc mentioned, this TriviadDriveKotlin is a temporary solution for online purchases. It is not safe and you can't access live data for your subscribers by Fireabase. We have to try and fix the issues for classytaxijava or classytaxikotlin. Currently I can't even build classytaxikotlin. and in the case of classytaxijava, it has some crash issues after complete installation and firebase setup. Even the codes are depricated and google doesn't care about it. I'll try to make some youtube videos step by step of the issues and put the links as the issues. Maybe someone care.

**Comment by DAGalpin** [comment]
This has been corrected in as much as it is possible. Without a server, there is no way to get notified of a subscription cancellation.  The client does check for purchase changes during onResume, and will update subscription status that way.
