### ISSUE TITLE
classytaxijava: how to see if the user is subscribed to basic or premium and toast a message

### ISSUE THREAD

**Issue by vafaminato** [android/play-billing-samples#319]
I can't find a way to see whether the user is subscribed (for example retrieve data from database or google play without internet access) and toast the result in main activity.
This is a simple question but was not implemented in the example.
I would appreciate if someone help.

**Comment by calren** [comment]
Once the [BillingClient](https://developer.android.com/reference/com/android/billingclient/api/BillingClient) is setup, you can query for existing subscriptions by calling [queryPurchases](https://developer.android.com/reference/com/android/billingclient/api/BillingClient#querypurchases). If you are specifically querying for subscriptions, it would look something like:
`billingClient.queryPurchases(BillingClient.SkuType.SUBS)`

**Comment by vafaminato** [comment]
Hello Caren.

What is this code (billingClient.queryPurchases(BillingClient.SkuType.SUBS)?
Is it a list or string? What if I want to get the price for the premium
subscription? Thanks
