### ISSUE TITLE
Where is ClassyTaxiAppWeb ?

### ISSUE THREAD

**Issue by agGitHub** [android/play-billing-samples#323]
Hi,

On this page:
https://github.com/android/play-billing-samples/tree/master/ClassyTaxiJava

is mentioned a 'a read-only web client to access the subscriptions on multiple platforms' but the folder:
https://github.com/android/play-billing-samples/tree/master/ClassyTaxiAppWeb

returns a 404 error.

Where can I find the ClassyTaxiAppWeb folder?

Thanks !

**Comment by calren** [comment]
Hey @agGitHub ! The web app is located here now: https://github.com/android/play-billing-samples/tree/master/ClassyTaxiServer/webapp. Sorry about that! I've updated the readme on https://github.com/android/play-billing-samples/tree/master/ClassyTaxiJava to reflect this as well. 

Thanks for pointing this out!

**Comment by agGitHub** [comment]
Thanks @cartland By the way, what is the purpose of this webapp? I don't understand what is it for.

Same question for the Backend Server code ; what is the purpose of this code ? What is it for ?
