### ISSUE TITLE
Google Play Inapp Billing v3: what is the purpose of Backend Server?

### ISSUE THREAD

**Issue by agGitHub** [android/play-billing-samples#324]
Hi,

I have an Android app with inapp subscriptions (with a 7 day free trial period) and I am trying to upgrade it to Google Play Inapp Billing v3 following these instructions:

https://github.com/android/play-billing-samples/tree/master/ClassyTaxiJava

I don't understand what is the purpose of the "Backend Server". What is it for ?

By the way, if you have any link to a detailed tutorial to deploy such a server (Google explanations given here https://github.com/android/play-billing-samples/tree/master/ClassyTaxiServer  are quite 'light'), I am interested :)

Thanks !

**Comment by calren** [comment]
Hey @agGitHub , good question! In my view, the main purpose of the backend server is to securely validate purchases by checking that each purchase token is unique. I agree that our documentation on the why and how of a backend server in relation to google play billing isn't the best, we'll look into how we can improve it.

**Comment by AsuwathamanRC** [comment]
Hey @agGitHub , you mentioned that you have an app with in-app subscription.  Could you please guide me on how to do it. I can't understand from the documentation and there are no tutorials for this.

**Comment by calren** [comment]
Closing issue since it's not related to samples.
