### ISSUE TITLE
Google Play Billing Pub/Sub (RTDN): Subscription Notification after free trial period?

### ISSUE THREAD

**Issue by agGitHub** [android/play-billing-samples#325]
Hi,

0

I wonder if Pub/Sub (RTDN) sends a notification when the payment occurs at the end of the free trial period (e.g.: 7 day free trial period).

Indeed, I see in [the doc](https://developer.android.com/google/play/billing/rtdn-reference):

_SUBSCRIPTION_PURCHASED - A new subscription was purchased._

(I understand that it is the free subscription, not the payment at the end of the free trial period)

_SUBSCRIPTION_RENEWED - An active subscription was renewed._

(I understand that it is a renewal after 1 year for a yearly subscription)

But I don't see a "SUBSCRIPTION_FIRST_PAYMENT" notification.

Thanks.

**Comment by calren** [comment]
RTDN doesn't specifically send a special notification when the user starts paying for the first time. However, you can track if a sub is in free trial via the `paymentState` field (https://developers.google.com/android-publisher/api-ref/purchases/subscriptions). And when the trial is over, a RTDN will be sent for the subscription having been 'renewed'. Hope that helps!

**Comment by agGitHub** [comment]
Thanks. It would be great to add a notification in RTND for this event. Regards.

**Comment by sorliem** [comment]
I have the same problem as @agGitHub.

@calren even looking at the `paymentState` and seeing `1` for 'payment received', there is still no context on if that was a first payment from a converted trial, or just a straight up regular first subscription purchase. 

I also don't see anything in `purchases.subscriptionsv2` that would indicate first-purchase-after-trial, is that correct?
