### ISSUE TITLE
Missing package "databinding".

### ISSUE THREAD

**Issue by rexthonyy** [android/play-billing-samples#333]
There appears to be a broken link to a "databinding" package which is non existent. It is supposed to hold the following fragments : FragmentHomeBinding, FragmentPremiumBinding and FragmentSettingsBinding

**Comment by calren** [comment]
Hey @rexthonyy , where are you seeing this issue? Are you seeing errors in Android Studio regarding databinding? Data binding can be a little wacky sometimes, and restarting Android Studio sometimes fixes the issue.

**Comment by calren** [comment]
I wasn't able to reproduce this error by running the ClassyTaxi samples, so I'm going to close this issue for now. If you have more info about when these errors pop up, please do add more comments to this issue!
