### ISSUE TITLE
Why taking so long for google people to reply to these issues is a big issue for itself

### ISSUE THREAD

**Issue by vafaminato** [android/play-billing-samples#336]
I think the content of this issue is self-explanatory.

**Comment by calren** [comment]
Hey @vafaminato , that's totally fair that the response time on these issues have not been great by any standards. Going forward, we're going to try and at least triage all issues within 72 hours.

**Comment by LordByron1788** [comment]
> Going forward, we're going to try and at least triage all issues within 72 hours.

What a waste of time. You basically gave up doing this after 2 weeks. Useless.
