### ISSUE TITLE
task.isSuccessful() = false / ServerError = NOT_FOUND

### ISSUE THREAD

**Issue by Wingx2** [android/play-billing-samples#338]
Hello, I have some problem , now i setup ClassyTaxiJava for learning Billing Subscriptions Process.
When i set USE_FAKE_SERVER = true(test the UI without the Firebase server), my app is Working!
it can get sku+token from Google Play & approval the function after subscription.

problem is here, When i set USE_FAKE_SERVER = False (Ues real firebase server), I get error...

```
firebaseFunctions
        .getHttpsCallable(SUBSCRIPTION_STATUS_CALLABLE)
        .call(null)
        .addOnCompleteListener(new OnCompleteListener<HttpsCallableResult>() {
           
@Override
public void onComplete(@NonNull Task<HttpsCallableResult> task) {
					
//---code--

   }
})
```

Result:
**task.isSuccessful() = false & ServerError get NOT_FOUND message 
"com.google.firebase.functions.FirebaseFunctionsException: NOT_FOUND"**
		
So I think still not complete Setup, I guess the problem is "service-account.json", i followed this tutorial
https://github.com/android/play-billing-samples/tree/master/ClassyTaxiJava#play-developer-console-setup

1. I Create a new private key from console.developers.google.com > APIs & Services > Service Accounts > Add Key, Create new Key & edit file name to service-account.json

2. Copy service-account.json to {project_folder}/ClassyTaxiServer/src/service-account.json

I think it's problem, i don't understand Which program will use/Call "ClassyTaxiServer/src/service-account.json" 

Any suggestions / example or Tips help me Solve this part
i am Beginner programmer, hope it won't waste too much time :-)

Thanks!

**Comment by Wingx2** [comment]
Update: 
I found it was not done correctly "Deploy Backend Server".

My solution
In my Case... Win10

1. "CMD" run as administrator

===CMD input command===
2. npm install -g firebase-tools 
3. npm install tslint typescript -g
4. npm install copyfiles -g
5. npm i googleapis
6. firebase login:ci
7. firebase init
Selected > "Functions: Configure and deploy Cloud Functions"
Selected > "TypeScript"
Created at this time > "C:\Windows\System32\functions" 
Cody [ClassyTaxiServer files](https://github.com/android/play-billing-samples/tree/master/ClassyTaxiServer) to "C:\Windows\System32\functions"

8.  firebase use --add {your_firebase_project_id}
9.  firebase functions:config:set app.package_name="your_android_application_id"
10. firebase functions:config:set app.basic_plan_sku="your_basic_subscription_product_sku_id"
11. firebase functions:config:set app.premium_plan_sku="your_premium_subscription_product_sku_id"
12. firebase deploy

It seems to install correctly, My ClassyTaxiApp also can load subscription function!

but I am not familiar with Server setup, I still don't fully understand how it work
EG..What config(TypeScript) do I need to change in my app in the future?
Any suggestions for setup Firebase in app subscription ?

Thank you!

**Comment by calren** [comment]
Hey @Wingx2 , thanks for following up with how you fixed your original issue!

If you build out a server exactly like ClassyTaxi's but tailored for your own app, steps 1-7 will remain the same. Steps 8-11 will depend on the specific variables tied to your server instance
