### ISSUE TITLE
Please test Google Play Billing Library in many devices and provide more corner cases to avoid "BillingClient.BillingResponseCode.BILLING_UNAVAILABLE"

### ISSUE THREAD

**Issue by antranvn** [android/play-billing-samples#339]
I saw many events:

`BillingClient.BillingResponseCode.BILLING_UNAVAILABLE`

**returned** in function:

` override fun onBillingSetupFinished(billingResult: BillingResult)`

in many devices, such as 
Oppo CPH1727, SM-N975F ....

My buildgradle:
```
billing_version = "3.0.0"
implementation "com.android.billingclient:billing:$billing_version"
implementation "com.android.billingclient:billing-ktx:$billing_version"
```

Please test the library in many devices as possible give us more specific solutions in case **BillingClient.BillingResponseCode.BILLING_UNAVAILABLE**

**Comment by calren** [comment]
Hey @antranvn , I believe this happens on phones that don't have the Play Store installed. Great call out that play billing library might not work on all devices, and it's important for the app to handle such cases.

**Comment by antranvn** [comment]
Thank you @calren , I saw most of the events coming from Iran. It seems they don't have the Play Store installed
