### ISSUE TITLE
Unexpected error when querying Google Play Developer API. Please check if you use a correct service account 

### ISSUE THREAD

**Issue by diogo10** [android/play-billing-samples#340]
Hi guys, I have this error over here and I do not understand what I am missing on the configurations:

![Screenshot 2020-08-17 at 14 37 49](https://user-images.githubusercontent.com/1541244/90402690-b8015500-e097-11ea-9cd2-8b655e32c91c.png)

The purchase comes OK on the onPurchasesUpdated method, but when it hits the cloud functions, I am getting this error.

Searching on the internet, there is a couple of comments saying that I have to wait for 24 after the setting up the service account. Is that true?

**_If the server service-account.json has changed, I have to delete the functions and deploy again?_**

**Comment by diogo10** [comment]
It's working now. I had to wait 24 hours. I will leave it here just in case someone else needs this info.

**Comment by calren** [comment]
Great! Thanks for the update @diogo10
