### ISSUE TITLE
GCP Service account

### ISSUE THREAD

**Issue by pedroafonso02** [android/play-billing-samples#343]
Hi ,
In the subscription_register function records I receive
"Unexpected error when querying Google Play Developer API. Please check if you use a correct service account".

The only part I haven't been able to fully understand is what are the roles I need to grant in creating a GCP service account. I think I'm missing this part.

What roles do I need to assign to this service account?

Thank you.

**Comment by MuhammadAjmal661** [comment]
I have Granted the role of Access Manager in play console. i have waited for 3-4 days, but still getting the same response. I am confused where is the mistake i am doing.
