### ISSUE TITLE
Replacing Fragment with Activity

### ISSUE THREAD

**Issue by vafaminato** [android/play-billing-samples#345]
Can you please replace the whole Fragments with three different Activities? It helps us a lot. Fragment binding to update the UI based on subscription is so complicated. Why not using one three activities and binding everything to it? I think many ones are more comfortable with activities than fragments (getting Lifecycles, context, etc.).

In the whole code example, there is not one single line to directly update the UI without connecting everything to each other (buttons to BillingViewModel. SubscriptionBindingAdapter and SubscriptionStatusViewModel to Fragment, etc.).

I need to update my main Activity UI without using the Fragment and it seems impossible (to get the grace period/not subscribed/subscribed status). For example how to attach the progress bar to the main activity layout?

**Comment by calren** [comment]
That's interesting feedback! It seems that's more of an Android architectural problem rather than a billing specific question though. Given that refactoring the whole app would take a considerable amount of effort, I don't think we have the bandwidth to tackle that within the next few months.
