### ISSUE TITLE
Typo issue in BillingViewModel.java

### ISSUE THREAD

**Issue by yanqinglu** [android/play-billing-samples#346]
Looks like there is a typo issue in BillingViewModel.java:

            // Only set the old SKU parameter if the old SKU is already owned.
            if (oldSkuToBeReplaced != null && !oldSkuToBeReplaced.equals(sku)) {
                Purchase oldPurchase = BillingUtilities
                        .getPurchaseForSku(purchases.getValue(), sku);
                billingBuilder.setOldSku(oldSkuToBeReplaced, oldPurchase.getPurchaseToken());
            }

It should be ".getPurchaseForSku(purchases.getValue(), **oldSkuToBeReplaced**);"?

**Comment by vegaro** [comment]
Someone has reported this already https://github.com/android/play-billing-samples/issues/328

**Comment by yanqinglu** [comment]
Thanks
