### ISSUE TITLE
In Production, the Google Billing still in test mode

### ISSUE THREAD

**Issue by diogo10** [android/play-billing-samples#348]
Hi guys, I have moved to Alpha to Production in order to test for real, but it still in test mode. How could I get it to make payment for real? Am I missing a setting?

**Comment by calren** [comment]
It might take a while (several hours) before the app is officially pushed to production. Were you still seeing this behavior after verifying that the app you're testing with is the one from production?

For a quick sanity check, I might delete the app and reinstall it from the play store just to make sure.

**Comment by calren** [comment]
Hopefully things are working as expected now, so we'll close this issue for the time being.

**Comment by MuhammadAjmal661** [comment]
Hi @diogo,
I think you are using tester email (email that is registerd in play console for testing subscriptions or in-app). Change your email address and then try.

**Comment by diogo10** [comment]
Hi guys, sorry for the later replying. The user did use a tester email, but we did took it from the tester list. After one day I guess, he was able to test with real money.
