### ISSUE TITLE
The current user has insufficient permissions

### ISSUE THREAD

**Issue by MuhammadAjmal661** [android/play-billing-samples#350]
Dear All,
I have created a service acount properly and integrated it to google play console and deployed server successfully.
when i perform any subscription then it's notification log is displayed in firebase cloud functions logs, but when i cancel subscription it throw error in logs which is given below:
realtime_notification_listener
Unexpected error when querying Google Play Developer API. Please check if you use a correct service account

realtime_notification_listener
{ OtherError: The current user has insufficient permissions to perform the requested operation. at PurchaseManager.convertPlayAPIErrorToLibraryError (/srv/lib/play-billing/PurchasesManager.js:337:30) at playDeveloperApiClient.purchases.subscriptions.get (/srv/lib/play-billing/PurchasesManager.js:123:37) at <anonymous> at process._tickDomainCallback (internal/process/next_tick.js:229:7) name: 'OtherError' }

i don't know why it is saying that insufficient permissions because i have properly given the permission(Release Manager)  access to service account .

kindly let me know when if any can help me.
Thank you.

**Comment by calren** [comment]
Hey @MuhammadAjmal661 , the first time you set up Google Play Developer API for your server, it may take about 24 hours for the correct permissions to show up. I would wait for a day and try it again. Let us know if it's still not resolved after the weekend.

**Comment by calren** [comment]
Hopefully it's working now after the initial wait period, so we'll close this issue

**Comment by MuhammadAjmal661** [comment]
Hy @calren , I have tested after 4 days it is still display same issue. I have given the access to service account as released Manager, but it still throw the same exception.
 
realtime_notification_listener
Unexpected error when querying Google Play Developer API. Please check if you use a correct service account

realtime_notification_listener
{ OtherError: The current user has insufficient permissions to perform the requested operation. at PurchaseManager.convertPlayAPIErrorToLibraryError (/srv/lib/play-billing/PurchasesManager.js:337:30) at playDeveloperApiClient.purchases.subscriptions.get (/srv/lib/play-billing/PurchasesManager.js:123:37) at at process._tickDomainCallback (internal/process/next_tick.js:229:7) name: 'OtherError' }

**Comment by MuhammadAjmal661** [comment]
Hi Caren,
After waiting long time the issue is still available. i have granted the
role as Released Manager but it is not working.
can you please help me in sorting this issue, i will be really thankful to
you for this help.

**Comment by MuhammadAjmal661** [comment]
> Hey @MuhammadAjmal661 , the first time you set up Google Play Developer API for your server, it may take about 24 hours for the correct permissions to show up. I would wait for a day and try it again. Let us know if it's still not resolved after the weekend.

Hi Caren,
I have waited for 3-4 days but still facing the same issue, can you please guide me how to handle permission

**Comment by MuhammadAjmal661** [comment]
Hi.
I have resolved the issue. I forgot to add scope in Google cloud console. I have added the scope and after 24 hours it is working fine.

**Comment by abhimuktheeswarar** [comment]
After updating the scope, try updating any in-app or subscription item, no need to wait for 24 hours.
