### ISSUE TITLE
Authenticating simultaneous account

### ISSUE THREAD

**Issue by vafaminato** [android/play-billing-samples#352]
I wonder what happens if a subscribed user share his/her account info (email in this case) with his/her friends. What happens then? Would the server log one out while using the app at the same time with another android device? Thanks.

**Comment by calren** [comment]
It depends on how you're implementing authentication, but regardless of the way you implemented authentication, you would have to specifically handle the case where two devices cannot be logged into the same account.

**Comment by vafaminato** [comment]
How is classytaxi java sample handling this? Can two devices be connected
at the same time? Is it not a security issue? If someone shares the
credential with a group of people.
