### ISSUE TITLE
拉起支付，提示“无法购买您要的商品”

### ISSUE THREAD

**Issue by lijibing892170** [android/play-billing-samples#354]
测试的版本已经发布到测试渠道，测试账号也加入了，拉起支付提示“无法购买您要的商品”

**Comment by yanqinglu** [comment]
The testing accounts must accept the testing invitation. Find it the testers email.

**Comment by lijibing892170** [comment]
> 测试帐户必须接受测试邀请。找到测试人员的电子邮件。

你好，我已经接受过邀请，依然提示“无法购买您要的商品”

**Comment by lijibing892170** [comment]
> 感谢您对@yanqinglu这个问题的帮助！
> 
> @ lijibing892170您可以在这里找到有关测试播放计费库的更多信息https://developer.android.com/google/play/billing/test
你好，按照文档的步骤，也不行

**Comment by lhxuan** [comment]
最后解决了吗？
