### ISSUE TITLE
TrivialDriveKotlin: 'getColor(Int): Int' is deprecated. Deprecated in Java

### ISSUE THREAD

**Issue by chaoslorenz** [android/play-billing-samples#356]
As per title, this message is appearing as a warning when the TrivialDriveKotlin sample is built:

"getColor(Int): Int' is deprecated. Deprecated in Java"

It relates to code in the SkuDetailsAdapter class.

**Comment by calren** [comment]
updated in https://github.com/android/play-billing-samples/commit/51e97690dd5343c2ab7970c0217e17cc177b7506
