### ISSUE TITLE
TrivialDriveKotlin: Unnecessary safe call on a non-null receiver

### ISSUE THREAD

**Issue by chaoslorenz** [android/play-billing-samples#357]
This warning message is appearing in multiple places, when the TrivialDriveKotlin sample is built.

In SkuDetailsAdapter.kt is appears here in line 78 and also on 101:

                itemView?.apply {
                    val name = title?.substring(0, title.indexOf("("))
                    sku_title.text = name
                    sku_description.text = description
                    sku_price.text = price
                    val drawableId = getSkuDrawableId(sku, this)
                    sku_image.setImageResource(drawableId)
                    isEnabled = canPurchase
                    onDisabled(canPurchase, resources)

In BillingRepository.kt it appears here in line 617:

                Log.d(LOG_TAG, "processPurchases purchases in the lcl db ${testing?.size}")

**Comment by calren** [comment]
updated in https://github.com/android/play-billing-samples/commit/51e97690dd5343c2ab7970c0217e17cc177b7506
