### ISSUE TITLE
TrivialDriveKotlin: DSL element 'annotationProcessorOptions.includeCompileClasspath' is obsolete.

### ISSUE THREAD

**Issue by chaoslorenz** [android/play-billing-samples#359]
Updating Gradle and Kotlin versions results in this message:

"DSL element 'annotationProcessorOptions.includeCompileClasspath' is obsolete"

Gradle lines amended:

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$version_kotlin"

where version_kotlin = 1.4.10

The project fails to build.

**Comment by calren** [comment]
updated in https://github.com/android/play-billing-samples/commit/51e97690dd5343c2ab7970c0217e17cc177b7506
