### ISSUE TITLE
TrivialDriveKotlin: Upgrade to use Billing library 3.0

### ISSUE THREAD

**Issue by chaoslorenz** [android/play-billing-samples#360]
Please can you upgrade this sample so that it uses the latest version of the Billing API 3.0.

Can you also update all the other references in this project.

They are all out of date.

It is very hard to implement Android billing when there is no clean sample to refer to that is not out of date.

Thank you,

**Comment by chaoslorenz** [comment]
Also, please ensure the ReadMe does not contain misleading information.

You have stated that TrivialDriveKotlin is a "Sample for In-App Billing version 3".

However, the project's Gradle clearly states that it is the following:

` version_billing = '2.0.1'`

**Comment by DAGalpin** [comment]
Corrected.  It was especially confusing because the README was very old and was referencing Play Billing 3.0 rather than the Play Billing Library 3.x.  It now uses PBL 3.x and the README file has been updated.
