### ISSUE TITLE
TrivialDriveKotlin: Multiple issues listed from doing 'Analyze>Inspect code'

### ISSUE THREAD

**Issue by chaoslorenz** [android/play-billing-samples#361]
In Android Studio 4.0.1, I ran the 'Inspect Code' under the 'Analyze' menu, on this project.

It has brought up many issues with this sample.

It seems to be in a very poor state.

Please could the ones related to the Billing code you have written be addressed.

Thank you,

**Comment by calren** [comment]
The project could use a bit of refresh to address those issues, but none of the issues seem related to the core billing logic so we haven't put it as a high priority. Let us know if you think there is certain code with issues related to the billing library!

**Comment by DAGalpin** [comment]
Addressed most of the relevant issues.
