### ISSUE TITLE
[Billing Client : 3.0.0] queryInAppTypeSkuDetails always returns error code 6 BUT old AIDL library works fine

### ISSUE THREAD

**Issue by manwithsteelnerves** [android/play-billing-samples#366]
We see always error code 6 with the following logs
1. Error : Billing unavailable for this package and user.
2. V/BillingClient: getDebugMessageFromBundle() got null response code, assuming OK
3. W/BillingClient: getSkuDetails() failed. Response code: 6

The above errors are with Billing client latest (3.0) version. Even we tried with older versions but no luck.

BUT

with the same test user, same project, same keystore, same package name and version code - old libraries with AIDL interface works fine.

This is a huge problem for us for its inconsistency as we need to update to billing client as AIDL is deprecated.
using AIDL libraries directly gives the proper sku details(using IABHelper).

Also tried clearing cache of google play multiple times but fundamentally, the same setup works with direct AIDL usage but not with google billing client.

Any info will be of great help.

**Comment by calren** [comment]
That definitely is not a great experience. I haven't been able to reproduce this myself, but we'll investigate further to see what might be going on here. We want to help everybody adopt the newest billing library, so thanks for filing this issue! Will update this thread if we have any updates or new findings.

**Comment by manwithsteelnerves** [comment]
Hey calren!
First of all Appologies. I figured it out that I was passing Array of array lists rather than Array of string for querying sku's.

It would be great if you guys have a check internally and throw the error accordingly. However, I purely accept its my mistake and unfortunately I had no clue why it was behaving that way.

Anyways, closing this issue.

**Comment by calren** [comment]
Glad it worked out in the end, thanks for the update!
