### ISSUE TITLE
BillingClient.queryPurchaseHistoryAsync returns an empty list on different device and after deleting the app from the same device

### ISSUE THREAD

**Issue by frukoyurdakul** [android/play-billing-samples#369]
According to [here](https://developer.android.com/google/play/billing/subs#account-hold), until November 1st, all apps have to handle the "Account Hold" status. That's good and all, and as long as we have the latest purchases, whether from history, or from locally saved spots, it is possible to track down whether the current user's subscription status is "Account Hold" or not. But, this comes with a problem:

If user deletes the app from the device, all the subscriptions are also deleted from Google's cache (at least that's what I understand.) which results in `BillingClient.queryPurchaseHistoryAsync()` return an empty list. This also happens if the purchase history is queried through another device using the same account. So, it is my belief that the purchase history is actually saved locally, or there is something weird going on that I cannot figure out.

Account Hold status requires Google Play Developer API to be integrated, and the subscription status is queried through that system using package name, subscription ID (sku) and purchase token. But, since `BillingClient.queryPurchaseHistoryAsync()` returns an empty list upon a successful query (`billingResult.getResponseCode() == BillingResponse.OK` is true) we have no subscription ID or purchase token to get the latest subscription state from.

This issue needs to be fixed ASAP on Google's side, or a solution must be posted here as Google is enforcing the Account Hold status to be implemented by November 1st. This will also help to follow paused subscriptions to be followed, which, I believe, will also be enforced in the future, but this problem is going on for ages.

Steps to reproduce:

1) Buy a subscription from your app.
2) Delete the app from the device.
3) Reinstall the app, and query purchase history.

Sample code to query purchase history (requires a live app to be tested, though):

```java
BillingClient client = BillingClient.newBuilder(application)
        .enablePendingPurchases()
        .setListener(new PurchasesUpdatedListener()
        {
            @Override
            public void onPurchasesUpdated(@NonNull BillingResult billingResult, @Nullable List<Purchase> list)
            {

            }
        })
        .build();
client.startConnection(new BillingClientStateListener()
{
    @Override
    public void onBillingSetupFinished(@NonNull BillingResult billingResult)
    {
        if (billingResult.getResponseCode() == BillingClient.BillingResponseCode.OK)
        {
            client.queryPurchaseHistoryAsync(BillingClient.SkuType.SUBS, new PurchaseHistoryResponseListener()
            {
                @Override
                public void onPurchaseHistoryResponse(@NonNull BillingResult billingResult, @Nullable List<PurchaseHistoryRecord> list)
                {
                    if (billingResult.getResponseCode() == BillingClient.BillingResponseCode.OK)
                    {
                        Log.d("BillingClient", String.format("List size is %d", (list != null ? list.size() : -1)));
                    }
                }
            });
        }
    }

    @Override
    public void onBillingServiceDisconnected()
    {

    }
});
```

You will see the purchase history will return an empty list (or a null list), even though Google Play Store is able to find the latest purchase, and a purchase was actually made. (Might not work for active subscriptions but it definitely is like this for Account Hold state.)

I am also open to hear an alternative to this. But please reply as soon as possible as we all have limited time here and probably everybody is suffering with this.

**Comment by calren** [comment]
Thanks for surfacing this! We have been actively working on issues like this for the past several months.

Given that issues filed here should be related to the samples and not the library itself, do you mind refiling this issue in our [public tracker](https://issuetracker.google.com/issues/new?component=311487&template=1014446)? 

This would allow the engineering team to reply with updates on the ticket filed. Thanks!
