### ISSUE TITLE
November 1st 2020 / 'Account Hold' : is it mandatory to display an explanatory message to 'Account Hold'  users ?

### ISSUE THREAD

**Issue by agGitHub** [android/play-billing-samples#373]
Hi,

It is mentioned [here](https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain-subscribers.html)  that a proper management of the 'Account Hold' status is required by November 1st, 2020.

The doc says [here](https://developer.android.com/google/play/billing/subs#account-hold) : "When a user enters into account hold, you should leverage Real-time developer notifications to inform your user why access to the subscription was suspended. Within your app, you should provide a message with instructions on how to fix their payment method and regain access to the subscription. Your message should include a link to the Google Play subscription settings so that they can fix their payment method. "

The problem is that the doc also says [here](https://developer.android.com/google/play/billing/subs) that it is not possible to differentiate the 3 statutes 'On Hold' 'Paused' 'Expired' if we use no backend server (+ RTDN and PubSub)

As we would really prefer not using backend server and RTDN, we wonder:
1) is it is really required to display a message to the user informing him/her that the subscription is Account Hold ?
2) if answer to 1) is 'yes', do we have to display a specific message for the 'Account Hold' status or can we display a message that covers the 3 statutes 'On Hold' 'Paused' 'Expired' ? (so that we can avoid the use of a backend server+RTDN)
3) do we have to display the message to the user only if he/she launches the app, or do we have to push a notification ?

Thanks a lot for your help.

**Comment by ashughes** [comment]
I second this inquiry. Here are related issues filed on the billing library issue tracker:

https://issuetracker.google.com/issues/154541074
https://issuetracker.google.com/issues/154538247

**Comment by calren** [comment]
Good question!

> is it is really required to display a message to the user informing him/her that the subscription is Account Hold ?
1. No, it's not required to display a message in-app about the user being in the 'account hold' state

If your app doesn't have a backend server that utilizes RTDN, [BillingClient.queryPurchases() ](https://developer.android.com/reference/com/android/billingclient/api/BillingClient#querypurchases) will still return all the active subscriptions for the user.

We recommend utilizing RTDN because it could allow your app to inform users why their subscription is in the 'account hold' state, but we also understand that not all developers have the bandwidth to also build out their own backend server just for this purpose. 

Hope that helps!

**Comment by agGitHub** [comment]
> Good question!
> 
> > is it is really required to display a message to the user informing him/her that the subscription is Account Hold ?
> 
> 1. No, it's not required to display a message in-app about the user being in the 'account hold' state
> 
> If your app doesn't have a backend server that utilizes RTDN, [BillingClient.queryPurchases() ](https://developer.android.com/reference/com/android/billingclient/api/BillingClient#querypurchases) will still return all the active subscriptions for the user.
> 
> We recommend utilizing RTDN because it could allow your app to inform users why their subscription is in the 'account hold' state, but we also understand that not all developers have the bandwidth to also build out their own backend server just for this purpose.
> 
> Hope that helps!

Thanks for this very helpful answer ! Best.
