### ISSUE TITLE
How to check if the subscription is active?

### ISSUE THREAD

**Issue by IlyaGazman** [android/play-billing-samples#374]
With the new subscription lifecycle
![image](https://user-images.githubusercontent.com/5740979/94706849-b66eb200-0310-11eb-9791-c55ece725f4b.png)

How to check if the subscription is active on the client-side without relying on a backend(real-time developer notifications)?

**Comment by calren** [comment]
`BillingClient.queryPurchases()` returns all active subscriptions without relying on a backend. Hope that helps!

**Comment by IlyaGazman** [comment]
@calren can you please clarify this. The description of `BillingClient.queryPurchases()` says:

> Get purchases details for all the items bought within your app

Will it return subscriptions in "Cancelled", "In grace period", "On Hold", "Paused" or "Expired" states?

**Comment by calren** [comment]
No, `queryPurchase()` will simply give you a list of subscriptions that are still active. In order to know what state the subscription is in, you would have to implement Real Time Developer Notifications for your backend.

**Comment by grrigore** [comment]
> No, `queryPurchase()` will simply give you a list of subscriptions that are still active. In order to know what state the subscription is in, you would have to implement Real Time Developer Notifications for your backend.

Is it possible to do it without a server? At the moment, a subscription it's cancelled and it shows as purchased and acknowledged, but [can purchase](https://github.com/android/play-billing-samples/blob/main/TrivialDriveKotlin/app/src/main/java/com/sample/android/trivialdrivesample/billing/BillingDataSource.kt#L237) it's true. What is the expected flow in this case?
