### ISSUE TITLE
TrivialDriveKotlin: Minimum SDK change

### ISSUE THREAD

**Issue by chaoslorenz** [android/play-billing-samples#379]
As a result of issue #355, in the commit 51e9769,  it looks like the minimum SDK has been changed from 14 to 23.

Can you confirm the reason? Does this mean that the current and future versions of the Billing library do not support older versions of Android?

In that case, how to handle billing that also needs to include older android versions?

Thank you

**Comment by calren** [comment]
The reason for that change was to target a higher SDK version that's more aligned with the majority of devices today. (minSDK 23 means that the app will still run on ~85% of all Android devices)

There are currently no plans for the billing library to not support older versions of Android.

**Comment by chaoslorenz** [comment]
> The reason for that change was to target a higher SDK version that's more aligned with the majority of devices today. (minSDK 23 means that the app will still run on ~85% of all Android devices)
> 

With all due respect, this is a poor reason.

The whole point of this sample, is to demonstrate how to implement the Billing Library and showcase it's capabilities. 

Being able to run on a wide range of Android versions is one such capability.

This is what the sample was demonstrating when the minimum sdk was at 14. I think this point was understood by the original developer when they set it at such a low number (when they could have opted for something higher).

The only reason to change the minimum SDK was if there was a breaking change with the Billing library or compatibility issues
with a core Android library in the sample. Any other reason is not a good one. There has been no change to the library version in this sample, to necessitate a change.

The choice of SDK 23 seems like a completely arbitrary decision. If issue #355 hadn't have been raised then it would not have been changed. Last time I checked, the other samples in this repository had different minimum SDK (some lower than 23). 

Why is there no consistency or quality checks for these samples?

The change in SDK may mean nothing to you, but they have ramifications for people leveraging these samples for their apps. This sample wrongly gives the impression you need to upgrade your min SDK to use the library, if you are following this implementation. If developers have existing users on older versions of Android, you are basically telling these developers to discard those users for no apparent reason.

Please think more carefully about such decisions in the future.
