### ISSUE TITLE
ClassyTaxiJava: login problem

### ISSUE THREAD

**Issue by codefarmer123** [android/play-billing-samples#380]
Hello,
Is it possible to subscribe without login or without using a third-party login?
If it can be done, please tell me how to do it.
Thank you

**Comment by calren** [comment]
It's possible to sell subscription products without implementing a login functionality (in which case the subscription would be attributed based on the current user logged in to Google Play). However, this would mean that the user would not be able to access the same subscription on an iOS device or the web. 

If your app doesn't include user logins, calling [queryPurchases](https://developer.android.com/reference/com/android/billingclient/api/BillingClient#queryPurchases(java.lang.String)) will return all the active subscriptions of the user currently logged in to Google Play.

**Comment by ashughes** [comment]
This is true as long as the user isn't logged into multiple Google accounts in Google Play and doesn't run into issue #2. :wink:
