### ISSUE TITLE
Why does "onPurchasesUpdated" method trigger many times in v3.0.1?

### ISSUE THREAD

**Issue by theozgurr** [android/play-billing-samples#387]
When you purchase a subscription/in-app product or close the offer screen, the "onPurchasesUpdated" triggers many times. And when you want to acknowledge non-consumable purchases, it gives this error many times except just one successful message: "Server error, please try again." You can check debug logs for more details and billing SDK that I'm using right now version is 3.0.1. Additionally, this behavior never occurred in the billing SDK v2. The method was always triggered just once and it was perfect :) Thanks.

When you close the offer screen:

**D/BillingManager: startPurchaseFlow(...), billingResult = 
D/BillingManager: purchasesUpdatedListener billingResult responseCode: 1
D/BillingManager: onPurchasesUpdated() - user cancelled the purchase flow - skipping
D/BillingManager: purchasesUpdatedListener billingResult responseCode: 1
D/BillingManager: onPurchasesUpdated() - user cancelled the purchase flow - skipping
D/BillingManager: purchasesUpdatedListener billingResult responseCode: 1
D/BillingManager: onPurchasesUpdated() - user cancelled the purchase flow - skipping
D/BillingManager: purchasesUpdatedListener billingResult responseCode: 1
D/BillingManager: onPurchasesUpdated() - user cancelled the purchase flow - skipping
D/BillingManager: purchasesUpdatedListener billingResult responseCode: 1
D/BillingManager: onPurchasesUpdated() - user cancelled the purchase flow - skipping
D/BillingManager: purchasesUpdatedListener billingResult responseCode: 1
D/BillingManager: onPurchasesUpdated() - user cancelled the purchase flow - skipping**

After your purchase:

**D/BillingManager: purchasesUpdatedListener billingResult responseCode: 0
D/BillingManager: acknowledgeNonConsumablePurchasesAsync called
D/BillingManager: purchasesUpdatedListener billingResult responseCode: 0
D/BillingManager: acknowledgeNonConsumablePurchasesAsync called
D/BillingManager: purchasesUpdatedListener billingResult responseCode: 0
D/BillingManager: acknowledgeNonConsumablePurchasesAsync called
D/BillingManager: purchasesUpdatedListener billingResult responseCode: 0
D/BillingManager: acknowledgeNonConsumablePurchasesAsync called
D/BillingManager: purchasesUpdatedListener billingResult responseCode: 0
D/BillingManager: acknowledgeNonConsumablePurchasesAsync called
D/BillingManager: purchasesUpdatedListener billingResult responseCode: 0
D/BillingManager: acknowledgeNonConsumablePurchasesAsync called
D/BillingManager: acknowledgeNonConsumablePurchasesAsync response is Server error, please try again.
D/BillingManager: acknowledgeNonConsumablePurchasesAsync response is Server error, please try again.
D/BillingManager: acknowledgeNonConsumablePurchasesAsync response is Server error, please try again.
D/BillingManager: nonconsumable purchased product: Purchase. Json: {same product...}
D/BillingManager: nonconsumable purchased product: Purchase. Json: {same product...}
D/BillingManager: nonconsumable purchased product: Purchase. Json: {same product...}**

**Comment by saitx** [comment]
We are having the same issue.

**Comment by calren** [comment]
Hey, thanks for letting us know about this! We mainly only triage issues related to the samples on Github. Do you mind refiling this issue on our official play billing issue tracker: https://b.corp.google.com/issues/new?component=311487&template=1014446 ? 

This will get the engineering team to take a look at this bug more quickly. Thanks!

**Comment by ashughes** [comment]
@calren That link is to your internal tracker at Google. The public issue tracker link is https://issuetracker.google.com/issues/new?component=311487&template=1014446

**Comment by calren** [comment]
@ashughes Ah, yes, great catch. Sorry about that!

**Comment by theozgurr** [comment]
@ashughes @calren It's done. Thanks for the link.
