### ISSUE TITLE
ClassyTaxiAppKotlin: No matching client found for package name 'com.xxx.xxx'

### ISSUE THREAD

**Issue by Kossi-Francois** [android/play-billing-samples#404]
may i have forgotten something but, I think I'm doing the right thing
I go to my firebase project,
I add an android app with the package name 'com.xxx.xxx'
I download the google-service.json file and put it in the project/app folder
i go to gradle.properties, i replace the package name: androidApplicationId = com.xxx.xxx
I perform the synchronization: BUILD SUCCESSFUL in 7s

but when I try to make the project or run it on device I have the error:  

          Execution failed for task ':app:processDebugGoogleServices'.
          > No matching client found for package name 'com.xxx.xxx'

and I do not understand why
I had already done this step about a month ago, but I had no problem and I am starting it again as part of another project and I have this error
Maybe a compatibility-release(ex dependencies) problem?
If anyone knows why or has a solution............
thank you in advance.

And I have checked my google-service.json file, and I have a client with "package_name": "com.xxx.xxx"

**Comment by Kossi-Francois** [comment]
And I tried with the ClassiTaxiJava project and it works so I think there is a problem with the Kotlin version, especially with the version of google services "com.google.gms: google-services"

**Comment by zubinxiong** [comment]
I have the same problems, after check the project, I found a debug folder it contains google-services.json file, you should change it to the file you download from firebase. Hope this can fix your problem
