### ISSUE TITLE
Steps to build the backend server code missing

### ISSUE THREAD

**Issue by polymake-pigeon** [android/play-billing-samples#407]
Please can you provide the steps to build the Classy Taxi backend server code?

I have added all of the code in Classy Taxi to my own app, following all of the given instructions, but I am not sure if I need to also edit the index.ts file and create new files for the backend server, as in the Classy Taxi Server example.  

This is my first Android app, and in iOS I have only used firebase for AdMob, so I need a little hand-holding. So far, I have completed all of the steps given for Classy Taxi and the only thing remaining to do is firebase deploy, which currently does not work - it seems I now have to upgrade to Blaze plan to enable this, but before I do that, I want to know if I have implemented everything else.

Also, I would like to know how to include a non-consumable 'premium upgrade' in-app purchase in the Classy Taxi example.

**Comment by polymake-pigeon** [comment]
So I worked it out for myself - I think!
Following the steps provided creates the index.ts file, but what it doesn't say is that you need to then add all of the functions for the firebase server.  
What is also not clear in the information provided in the example, is that rather than putting all of the functions directly into the index.ts file, you can divide the functions between many files, which you create yourself, and organise in folders as per the Classy Taxi Server Structure, with the index.ts linking them together (well that's my understanding anyway!).

All of this needs to be done after you have installed Node.js, npm and Firebase CLI, but before completing the steps to Deploy the Backend Server.

What is also confusing to someone new to all of this, is how to create files like those in the Classy Taxi Server example.  The index.ts file is automatically generated, so I did not know if the other files would be also automatically generated by running a command, or if - as I eventually figured out - the files and folders can be optionally generated manually.  Other newbies might find it useful to know that I used VS Code to do this.

I hope this helps any other beginners who have been struggling like myself!
It would be good if the 'Read Me' for this project was updated to include this information.

**Comment by cartland** [comment]
@polymake-pigeon I'm glad to hear you figured it out. The README for the Classy Taxi Server was updated recently. Hopefully the new README is more helpful.

https://github.com/android/play-billing-samples/blob/4e4b6036645a1655cc0724c364258400449f0190/ClassyTaxiServer/README.md

**Comment by calren** [comment]
Thanks @polymake-pigeon for the clarifications on how you got the deployment to work. Hopefully the new updated README will be helpful for future developers as well. Closing this issue for now since there are no actionable items left.
