### ISSUE TITLE
TrivialDriveKotlin Build Error (Cannot find getter for field.)

### ISSUE THREAD

**Issue by kskbeko** [android/play-billing-samples#412]
This is the error code when i trying the build source code of TrivialDriveKotlin
Whats wrong ? please help.

Thanks in advance. Best regards

> Task :app:kaptReleaseKotlin
C:\Users\PC\Desktop\Android\TrivialDriveKotlin\app\build\tmp\kapt3\stubs\release\com\kotlin\trivialdrive\billingrepo\localdb\CachedPurchase.java:34: error: Cannot find getter for field.
    private int id = 0;
                ^C:\Users\PC\Desktop\Android\TrivialDriveKotlin\app\build\tmp\kapt3\stubs\release\com\kotlin\trivialdrive\billingrepo\localdb\Entitlement.java:13: error: Cannot find getter for field.
    private int id = 1;
                ^[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.lifecycle.LifecycleProcessor (NON_INCREMENTAL), androidx.room.RoomProcessor (NON_INCREMENTAL).

> Task :app:kaptReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 4s
12 actionable tasks: 1 executed, 11 up-to-date

**Comment by calren** [comment]
@kskbeko I was able to check out the current version of ClassyTaxiKotlin and build it on my local machine, so I'm not sure where your issue is coming from.

A few things to try:
- Cleaning and rebuilding the project
- Invalidate caches and restart Android Studio

**Comment by DAGalpin** [comment]
TrivialDriveKotlin should build correctly now.
