### ISSUE TITLE
Fix your shit on queryPurchases()

### ISSUE THREAD

**Issue by diaconori** [android/play-billing-samples#413]
Issue has been going on for YEARS. 

Still returns all subscriptions regardless of their states. Let us be able to check states from the devices. Not all of us want to invest in a client server architecture, especially when you are advocating for a serverless architecture LOL.

**Comment by calren** [comment]
Thanks for the feedback. We like to keep this repo contained to issues regarding the samples, but if you have a feature request for the Play Billing library, feel free to file it on our [issue tracker for the Play Billing library](https://issuetracker.google.com/issues/new?component=311487&template=1014446). Since this issue isn't directly related to the samples, we'll be closing it for now.

**Comment by LordByron1788** [comment]
> We like to keep this repo contained to issues regarding the samples, but if you have a feature request for the Play Billing library, feel free to file it on our [issue tracker for the Play Billing library]


The original commentator made a point about developers have a requirement for serverless billing. 

Where is the Java sample version showing serverless billing?

Why is the Kotlin version for serverless billing out of date?

**Comment by diaconori** [comment]
What a joke. It was basically a polite way of saying fuck you to me and this issue.

**Comment by cartland** [comment]
> `[queryPurchases()]` Still returns all subscriptions regardless of their states.

This is an accurate description of the behavior of the API.

> Let us be able to check states from the devices.

This is a valid feature request. You can submit feature requests in the [issue tracker for the Play Billing library](https://issuetracker.google.com/issues/new?component=311487&template=1014446).

> Not all of us want to invest in a client server architecture

Based on conversations with developers, most developers without a server simply need to know if the purchase is active. Even if they had the details of the subscription, they wouldn't use any information except whether the subscription is currently active. Many other developers use a server so they can manage subscriptions across multiple devices and platforms, so they need additional details. If you do not want to use a server and you need additional API features, please share more details about your feature request in the [issue tracker for the Play Billing library](https://issuetracker.google.com/issues/new?component=311487&template=1014446).

I can see that you are unhappy with the current situation. I would like to ask you to follow our suggestions so that we can better understand what you and other developers need.

**Comment by diaconori** [comment]
They wouldn't use that information at all? Okay. Please do explain the reactions of the developers on this issue then: https://github.com/android/play-billing-samples/issues/122

Isn't it the exact same problem that I am addressing here? Any developer obviously has a need to check the state information of the user's subscriptions, as well as when it is expiring etc. You've been advocating for serverless architecture ever since Firebase and Firestorm has become a thing. It shouldn't come as a surprise to you that developers are begging for this feature for YEARS, hence if it weren't a basic need then you wouldn't have implemented a quota usage for your APIs to access that very same information. 

Again. Fucking stupid. This is the kind of bs that makes people migrate their products to iOS.

**Comment by diaconori** [comment]
Another one. Perhaps we should make a collection of these, don't you think?

https://github.com/android/play-billing-samples/issues/367

**Comment by diaconori** [comment]
If you want developers to elevate the platform then give them the tools and opportunities to do so.

**Comment by diaconori** [comment]
They wouldn't use that information at all? Okay. Please do explain the reactions of the developers on this issue then: #122'
Oh. Another one: https://github.com/android/play-billing-samples/issues/367

Perhaps we should make a collection of these, don't you think?

**Comment by alfonsoperez** [comment]
Seems related to https://github.com/android/play-billing-samples/issues/122

**Comment by GrosserStuhl** [comment]
Unbelievable how this has been going on for years.

A user switches phones and suddenly loses all his purchases if I don't have my own backend running checks constantly?? What the hell...

**Comment by LordByron1788** [comment]
> They wouldn't use that information at all? Okay. Please do explain the reactions of the developers on this issue then: #122
> Oh. Another one: #367
> 
> Perhaps we should make a collection of these, don't you think?

This Github is resembling a Kafkaesque knight mare.

**Comment by diaconori** [comment]
I've deleted the trash modules (provided by everyone's favourite) and migrated to RevenueCat's services. Some legend from issue 122 was kind enough to inform us about it. I'd encourage you all to do the same.

Oh and also, while you're doing this, try to search on Google and find out about how much RevenueCat is actually making on this kind of service alone (handling in-app purchases and subscriptions)... It seems to me that Google has a large stake in this since they don't give a damn about these issues.

**Comment by GrosserStuhl** [comment]
> I've deleted the trash modules (provided by everyone's favourite) and migrated to RevenueCat's services. Some legend from #122 was kind enough to inform us about it. I'd encourage you all to do the same.
> 
> Oh and also, while you're doing this, try to search on Google and find out about how much RevenueCat is actually making on this kind of service alone (handling in-app purchases and subscriptions)... It seems to me that Google has a large stake in this since they don't give a damn about these issues.

Does RevenueCat work for past purchases, i.e. if I implement it now, does it work for people who already purchased, or only new ones who purchase after I implement it?
Also, did you have some good tutorial to follow along besides their documentation? I just want to make sure I don't miss anything.

**Comment by diaconori** [comment]
> > I've deleted the trash modules (provided by everyone's favourite) and migrated to RevenueCat's services. Some legend from #122 was kind enough to inform us about it. I'd encourage you all to do the same.
> > Oh and also, while you're doing this, try to search on Google and find out about how much RevenueCat is actually making on this kind of service alone (handling in-app purchases and subscriptions)... It seems to me that Google has a large stake in this since they don't give a damn about these issues.
> 
> Does RevenueCat work for past purchases, i.e. if I implement it now, does it work for people who already purchased, or only new ones who purchase after I implement it?
> Also, did you have some good tutorial to follow along besides their documentation? I just want to make sure I don't miss anything.

No documentation for Android on YouTube... None. I had to go through the documents but luckily, I got it to work. 

It will work for anything. They made it very well. So once you're done implementing it with RevenueCat, you can come back to this issue and leave a little comment for Google :-)

**Comment by vegaro** [comment]
First of all, I work for RevenueCat. Happy to read you are finding our services helpful 😇 

We have a guide for migrating your current system to RevenueCat https://docs.revenuecat.com/docs/migrating-existing-subscriptions

Feel free to reach us in our Spectrum chat https://spectrum.chat/revenuecat or contact our support team directly https://www.revenuecat.com/contact. We’ll be happy to answer any question you have. I monitor this repo, but our support team can surely help you with anything.

Cheers!
