### ISSUE TITLE
Forking project result in a 2015 copy of master and not present day version repo

### ISSUE THREAD

**Issue by adozenlines** [android/play-billing-samples#414]
Fix the forking branch to main or update master.

**Comment by codingjeremy** [comment]
I just forked from github and it forks the default branch, `main`.  Also, I have a Github Action that runs for every commit on `main` and copies it over to `master`. I just checked and `master` is matched up with the latest `main` commit.

Is there maybe something else that is going on or maybe you are talking about a different fork?

@calren as FYI

**Comment by calren** [comment]
I also wasn't able to reproduce the issue. I [forked the repo](https://github.com/calren/play-billing-samples) and it's a copy of  https://github.com/android/play-billing-samples
