### ISSUE TITLE
Google Play Billing Pub/Sub (RTDN): linkedPurchaseToken after resubscribing from an expired subscription

### ISSUE THREAD

**Issue by iammart** [android/play-billing-samples#420]
Hello,

I understand that when a user resubscribes from a cancelled but not expired subscription, that a `SUBSCRIPTION_RESTARTED` is published. This event will give me information on the original `purchaseToken` via `linkedPurchaseToken`.

When a user resubscribes in the period after the subscription expiring it creates a new subscription with a new  `purchaseToken`,  and publishes a `SUBSCRIPTION_PURCHASED` event. 

As this can be action from outside the app, how is the server that subscribes to the  event able to identify the user the original subscription belongs to if `SUBSCRIPTION_PURCHASED` fails to contain a `linkedPurchaseToken`?

Thanks,

**Comment by voxmate-gleb** [comment]
I am looking for the same information. Have you found a solution?
