### ISSUE TITLE
Play Protect Error In All Project

### ISSUE THREAD

**Issue by Atulup** [android/play-billing-samples#424]
Hello, Suddenly 14-15 days ago i got play protect error in my one project when i generate signed apk then i was i was getting this in my all previous projects to also if i create new project their also getting this play protect error while installing.

I filled appeal waited for 7-8 days then again i open android and build apk then also i was getting play protect error while installing application. Will you help me to fix and what is published the application having play protect error does it will affect my console.

**Comment by tata406** [comment]
### 
### 
## 
#

**Comment by tata406** [comment]
###

**Comment by calren** [comment]
This repo focuses on play billing specifically. I suggest posting your question on StackOverflow with more information about the specific error you're seeing. 

Example issues on Play Protect from StackOverflow:
https://stackoverflow.com/questions/54748129/blocked-by-play-protect-released-apk 
https://stackoverflow.com/questions/51587544/released-apk-installed-in-android-device-is-error-blocked-by-play-protect
https://stackoverflow.com/questions/51344169/debug-app-blocked-by-play-protect
