### ISSUE TITLE
TrivialDrivalKotlin: ReadMe incorrectly states sample uses Billing version 3.0 - actually it is only using 2.0 

### ISSUE THREAD

**Issue by chaoslorenz** [android/play-billing-samples#425]
I flagged this up on issue #360 

This is false and completely misleading information.

Google do not seem to care about these samples at all.

If you have been sent an email from Google this week, about updating your apps to version 3.0, please note there is no sample
for the "TrivialDrive app" to show you how to do this.

**Comment by DAGalpin** [comment]
This is indeed confusing, made more so because it's talking about Billing 3.0, which is the third version of Google Play in-app purchases (where subscriptions were first added), and not Billing Library 3.0, which includes a bunch of other features and improvements.

**Comment by DAGalpin** [comment]
Updated/rewrote the sample to use Billing Library 3.0, and also clarified the description.
