### ISSUE TITLE
Has this repository been completely abandoned?

### ISSUE THREAD

**Issue by chaoslorenz** [android/play-billing-samples#426]
Google is forcing us to to update our apps to use their new Billing library 3.  Developers have been given firm deadlines with which to comply this year.

However, issues are not being addressed, and the samples are not being updated.

Why is Google not helping with these?

**Comment by KeyPuncherBe** [comment]
I've been asking the same questions. 

I've been developing on other platforms than Android. But Android is the worst, ..., by far!

Code samples in documentation is often no where to be found in the official samples.

**Comment by JoneJay** [comment]
Google code's quality is RUBISH!

**Comment by DAGalpin** [comment]
It hasn't been abandoned.  That being said, I agree that it would be ideal for snippets within documentation to be buildable samples.

**Comment by chaoslorenz** [comment]
> It hasn't been abandoned.

Feels like it
