### ISSUE TITLE
Trivial Drive Kotlin sample should be deleted

### ISSUE THREAD

**Issue by thubalek** [android/play-billing-samples#427]
I spend a lot of hours trying to review and understand this sample and I found that
- it is not reusable. It tried to include it in my application and I gave it up after one day
- it is poorly designed and violating good OOP principles 

_*It is more confusing than helpful.*_

My suggestion for others: look at https://github.com/android/play-billing-samples/blob/main/ClassyTaxiAppKotlin/app/src/main/java/com/example/subscriptions/billing/BillingClientLifecycle.kt

It is much better designed, has low coupling with client application and is up to date (uses billing 3.x instead of 2.x). `BillingClientLifecycle` is good start for your app's implementation.

On my opinion Google should make something like `jetpack-billing` that will encapsulate trivial usages of billing into simple reusable and easy to integrate API that does not use `LiveData` but listeners/callbacks/coroutines. `LiveData` may be replaced with something in near future but listeners/callbacs/suspend fun will be here much longer.

To be honest: I think that most developers just needs to be able 
- get list of SKUs that can be purchased
- be able buy SKU
- get information what SKUs are currently active

**Comment by calren** [comment]
Thanks @thubalek for writing up the detailed feedback. I agree there is a lot of room for improvement in terms of TrivialDriveKotlin. 

Having a `jetpack-billing` library does sound like it could be helpful, and definitely something worth considering.

In the meantime, we'll look into whether we should deprecate TrivialDrive completely and replace it with a simpler to follow sample.

**Comment by thubalek** [comment]
I would suggest to write minimal example around `BillingClientLifecycle.kt`. It looks like solid piece of code, quite easy to understand.

Please make it reusable
- so no hardcoded SKUs
- developer public key as parameter
- notifications via callbacks or via Kotlin Coroutines Flow
- no caching as Billing Client v3 should have built in caching 

UI screen should be extremely simple:
- one consumable product 
- one subscription

**Comment by DAGalpin** [comment]
I've rewritten the TrivialDriveSample around something closer to BillingClientLifecycle, although I've abstracted all the app-specific code into the repository class. The Java version uses LiveData, while the Kotlin version takes advantage of SharedFlow/StateFlow.

**Comment by thubalek** [comment]
@DAGalpin good job. I like new implementation. Clean separation of responsibilities. Reusable.
