### ISSUE TITLE
Why is the TrivialDriveKotlin's billing version is 2.0.1???But in the Readme.md it says version 3.....................

### ISSUE THREAD

**Issue by JoneJay** [android/play-billing-samples#438]
https://github.com/android/play-billing-samples/blob/master/TrivialDriveKotlin/build.gradle   :  45

version_billing = '2.0.1'

**Comment by khanhnt3010** [comment]
hi @JoneJay, the reason: https://github.com/android/play-billing-samples/pull/432

**Comment by JoneJay** [comment]
> hi @JoneJay, the reason: #432

OK，but I think it also shold be removed from https://github.com/android/play-billing-samples ' s  readme, I came from there.

**Comment by khanhnt3010** [comment]
I'm still waiting for owner's answer, but nothing :(
