### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by liupeng110** [android/play-billing-samples#439]
run empty!

**Comment by liupeng110** [comment]
![aaa](https://user-images.githubusercontent.com/9512550/114681961-3aced280-9d41-11eb-9d72-2754db4638b8.gif)

**Comment by khanhnt3010** [comment]
the answer is: https://github.com/android/play-billing-samples/pull/432

**Comment by DAGalpin** [comment]
The updated TrivialDriveKotlin has much better error handling, so it should help these scenarios.
