### ISSUE TITLE
Using BillingDataSource.java in my App

### ISSUE THREAD

**Issue by blotfi** [android/play-billing-samples#459]
Dear all
I am trying to use 
BillingDataSource.java
Security.java
from TrivialDriveSample
I managed to get the purchase for a Premium SKU (Once puchase)
but where can I check if this product is bought when my App start in order to unlock features each time the App starts
I need to call from my MainActivity a method to see if it is ok

if I ask
```
        @Override
        public void onResume() {
            super.onResume();
            LiveData<Boolean> IsPremiumPurchased = ((MainActivity)getActivity()).billingDataSource.isPurchased(SKU_PREMIUM);
            mIsPremium = IsPremiumPurchased.getValue();
            Log.d(TAG, "User is " + (mIsPremium ? "PREMIUM" : "NOT PREMIUM"));
            ((MainActivity)getActivity()).updateUi();
        }

```
I got
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at com.xxxxxxxxxxx.MainActivity$MainFragment.onResume(MainActivity.java:1302)

because IsPremiumPurchased  is not valid

**Comment by chaoslorenz** [comment]
> but where can I check if this product is bought when my App start in order to unlock features each time the App starts

Yes, this is what I have been trying to figure out as well. The sample obscures what is the most basic and most fundamental of tasks.

**Comment by blotfi** [comment]
no answer ?

**Comment by chaoslorenz** [comment]
> no answer ?

You have to wait a few months, and then maybe somebody will respond.

**Comment by blotfi** [comment]
I posted my question on 
https://stackoverflow.com/questions/67818644/using-billingdatasource-java-of-android-example?noredirect=1#comment120258500_67818644

put a bounty on it and get an answer
now my App is online:
https://play.google.com/store/apps/details?id=com.embesystems.dcm
with help files on:
http://www.embesystems.com/app/

**Comment by chaoslorenz** [comment]
I think it's a waste of time posting on this github repository
