### ISSUE TITLE
Question: why does "Purchase" have a list of SKUs ? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/play-billing-samples#461]
It seems that recently it changed from one to multiple ones:
https://developer.android.com/reference/com/android/billingclient/api/Purchase#getSkus()

Can users perform a single purchase of multiple SKUs ? 
Are they guaranteed to be of the same type (subscription, for example) ? 

The sample seems to handle just the first item of it:

![image](https://user-images.githubusercontent.com/5357526/121002496-11f11980-c795-11eb-84ea-40ed450f5179.png)

So, what's going on? Why isn't it documented?

**Comment by vegaro** [comment]
Google announced that later in 2021 there is going to be multi-line subscriptions and multi quantity consumable support

**Comment by AndroidDeveloperLB** [comment]
@vegaro Later than what?
Also, is it guaranteed that a purchase will have only one type of product (subscriptions or consumable but not both) ? 
Otherwise I don't know how it should be handled...
Is the API ready for multi-purchases in a single purchase?

**Comment by vegaro** [comment]
I honestly don't know, I don't work at Google. I am assuming there's one sku, that's for sure. If would be great if someone from Google could jump in and give some more information to prepare our backend and apps

**Comment by AndroidDeveloperLB** [comment]
@vegaro I think you mean "at least one sku".

**Comment by vegaro** [comment]
Sure. I only take into account the first one in the list for now, as they do in this repository's sample https://github.com/android/play-billing-samples/blob/f9ae2d55c3699474e26ca0185a5ff38afb9df153/ClassyTaxiAppKotlin/app/src/main/java/com/example/subscriptions/ui/MainActivity.kt#L149

**Comment by AndroidDeveloperLB** [comment]
@vegaro  I know. It's on the screenshot I've put...

**Comment by AndroidDeveloperLB** [comment]
@vegaro Can you please show me about the announcement you were talking about?
Maybe it has some other things I should know about.

**Comment by vegaro** [comment]
@AndroidDeveloperLB https://android-developers.googleblog.com/2021/05/whats-new-in-google-play-2021.html

**Comment by AndroidDeveloperLB** [comment]
@vegaro Thank you. It became harder and harder to keep up with those videos. In the past I've watched them all. Now I have to focus on what I think is more important based on what I work with.
