### ISSUE TITLE
SKU not found

### ISSUE THREAD

**Issue by jclson007** [android/play-billing-samples#508]
I followed this instruction, but still error SKUs not found.

8. Under In-app Products, create products with these Product IDs: premium, gas
9. Under Subscriptions, create SUBSCRIPTION items with these IDs: infinite_gas_monthly, infinite_gas_yearly

hope anyone can help me thanks.

**Comment by oussemaRidene** [comment]
Hey @jclson007 can you give me the instructions or documentation that you followed to diplay sku list ?
