### ISSUE TITLE
Retrofit Service Interface SubscriptionStatusApiCall does not register instance id

### ISSUE THREAD

**Issue by nkhar** [android/play-billing-samples#510]
SubscriptionStatusApiCall contains incorrect signature for registering instance Id. It registers subscriptions instead.

https://github.com/android/play-billing-samples/blob/3a4c729e0e4e2a4151ab274decf5608726512690/ClassyTaxiAppKotlin/app/src/main/java/com/example/subscriptions/data/network/retrofit/SubscriptionStatusApiCall.kt#L30
https://github.com/android/play-billing-samples/blob/3a4c729e0e4e2a4151ab274decf5608726512690/ClassyTaxiAppKotlin/app/src/main/java/com/example/subscriptions/data/network/retrofit/SubscriptionStatusApiCall.kt#L31

**Comment by cka-dev** [comment]
Thanks for reporting this @nkhar, and apologies for the very late response.
This should be fixed now.

Cheers
