### ISSUE TITLE
How to Transfer using Google Developer API?

### ISSUE THREAD

**Issue by tfrysinger** [android/play-billing-samples#512]
The ClassyTaxi app seemingly has the ability to "transfer" a purchase made with one Google Play Account to another (i.e. "Wrong Taxi?"). Yet in trying to implement this in my own app I don't find any Google Developer API way to do this. How can I programmatically cause a purchase made with one Google Play Account to be "transferred" to another - am I missing something? Also asked this on StackOverflow [here](https://stackoverflow.com/questions/70598465/how-do-i-implement-google-play-account-transfer-as-shown-in-classytaxi).

**Comment by cartland** [comment]
The "Transfer" feature in ClassyTaxi reassigns a purchase to a different ClassyTaxi account. This doesn't transfer the subscription to a different Google Play account. The change happens in the ClassyTaxi database, not the Google Play Developer API.

Here is an example user flow:

1) Sign in to ClassyTaxi with a@example.com
2) Subscribe using the Google Play account on the device: z@gmail.com
3) Sign out of ClassyTaxi
4) Sign in to ClassyTaxi with b@example.com
* At this point, the Google Play subscription for z@gmail.com is returned from the Google Play Billing Library, the subscription is associated with a@example.com, and the user is signed in with b@example.com.
5) Transfer the subscription bought with z@gmail.com from account a@example.com to b@example.com
* At this point, the subscription is associated with b@example.com, and the user is signed in with b@example.com.

**Comment by tfrysinger** [comment]
Ah, ok. My confusion. Not a use case for me at this point (at least, it
isn't from my Android app perspective - if a user wants to change their
existing app login in my app to a different email address they can do so
but this is all handled on the back-end, including reconciling existing
purchases), but thanks for the clarification!

**Comment by cartland** [comment]
@tfrysinger yes that's the right idea. I would also say that this is handled in the "back-end" of ClassyTaxi -- but we also put a button in the Android app so the user can tell us to make the update to the database.
