### ISSUE TITLE
querySkuDetailsAsync Listener calls in wrong thread

### ISSUE THREAD

**Issue by SharyRajpoot** [android/play-billing-samples#517]
I have just recently updated the latest version of the `Google Billing Lib. 4.1.0` from 3.0.2.
I don't know how exactly to define this issue but will try my best.
Now what I noticed when I call `querySkuDetailsAsync` with the listener and inside this listener, I am printing products SKUs prices to the device screen,
In the newer version, an exception was thrown like `Only the original view can touch its view hierarchy` as you can notice it's like the listener just went to a background thread or its code execution is happening in the background thread.
Now you say it might be my code has something to do with it BUT actually, it's not...
As I have downgraded to the older version its working fine with the same source code...
So it's not really a source code problem but something with a newer version of the library.

**Comment by SharyRajpoot** [comment]
I have found after making a connection with the billing client on `billingClient.startConnection(object : BillingClientStateListener......` the code from here changes the thread...don't know why..

**Comment by SharyRajpoot** [comment]
Well, I have found this your new v4 billing lib. the implementation, that you have annotated some methods with `@AnyThread` and all listeners that I am using to receiver a billing response for different APIs like `startConnection, querySkuDetailsAsync...etc` all are causing thread change which somehow does not let the UI updates directly.
Now I have to explicitly move this thread processing manually to Main Thread using coroutines and after this, all UI updates work normally...but still it's just a hack and I want a reason why is this happening with your v4 of billing lib.
e.g:
`
CorotineScope(Dispatcher.Main).launch {
     // UI Operations...
}
`

As I said in the above comment I need to display price data for in-app inside app UI on `querySkuDetailsAsync `.

**Comment by stephanedupont** [comment]
I don't know why you would assume that a listener from an async operation would be called from the main thread.

What you are doing is absolutely not a hack, but what you are supposed to do: if you need to update UI from a callback that is called from async work, you have to do what you mention in your last comment, explicitly execute the code on the main thread.

**Comment by SharyRajpoot** [comment]
Oh, then it means it's not a bug but the implementations that you have done so. Actually, as I said in my first comment after getting a response from `querySkuDetailsAsync` in the listener `querySkuDetailsAsync -> onSkuDetailsResponse` i am displaying SKU's or you can say products price to screen so users can know what they need to pay for a specific package within the app.
Like this below for example.
e.g:
`
6 Month             $ 2.99
1 Year                 $ 3.99
`

So that's why I need to update the UI with-in the `querySkuDetailsAsync`. Anyways thanks for clearing me on this I thought it was some bug with this lib. new version. I'll use the coroutine functions for UI updations where needed. :)

**Comment by gomigbg** [comment]
I think that this is actually a bug.  The documentation for BillingClient says
`All methods annotated with [AnyThread](https://developer.android.com/reference/androidx/annotation/AnyThread) can be called from any thread and all the asynchronous callbacks will be returned on the same thread. Methods annotated with [UiThread](https://developer.android.com/reference/androidx/annotation/UiThread) should be called from the Ui thread and all the asynchronous callbacks will be returned on the Ui thread as well.`
(https://developer.android.com/reference/com/android/billingclient/api/BillingClient)

And querySkuDetailsAsync is marked AnyThread, so I would expect that if you call it on the UiThread, then the callback would be called on the UiThread.

**Comment by grog444** [comment]
Why is this issue closed? The documentation should be updated from 

> All methods annotated with [AnyThread](https://developer.android.com/reference/androidx/annotation/AnyThread) can be called from any thread and all the asynchronous callbacks will be returned on the same thread

to 
 
> All methods annotated with [AnyThread](https://developer.android.com/reference/androidx/annotation/AnyThread) can be called from any thread and all the asynchronous callbacks will be returned on some single thread that may or may not be the calling thread.

Since that's what I'm forced to assume it means.
