### ISSUE TITLE
 Implementing QueryProductdetails (Billing client 5.0.0)

### ISSUE THREAD

**Issue by ryderz8** [android/play-billing-samples#531]
From the _subscriptionOfferDetails_ object obtained using the **queryProductDetailsAsync**, how can we identify the offer(s) attribute(s) that allow us to know if an offer is a free trial or an introductory discount? Could you share with us how we could be able to do this?

```
"subscriptionOfferDetails": [
    {
      "offerIdToken": "AXDE.......",
      "pricingPhases": [
        {
          "priceAmountMicros": 86290000,
          "priceCurrencyCode": "EUR",
          "formattedPrice": "€86.29",
          "billingPeriod": "P1Y",
          "recurrenceMode": 2,
          "billingCycleCount": 1
        },
        {
          "priceAmountMicros": 95880000,
          "priceCurrencyCode": "EUR",
          "formattedPrice": "€95.88",
          "billingPeriod": "P1Y",
          "recurrenceMode": 1
        }
      ],
      "offerTags": [
        
      ]
    }
```

**Comment by cka-dev** [comment]
@ryderz8 I'd suggest leveraging offerTags for this. For example you could add the tag "freetrial" to all your free trial offers vs the tag "introdiscount" for introductory discounts. 

Hope this helps.
Cheers

**Comment by ryderz8** [comment]
Thanks, @cka-dev for getting back to me! 
In the above sample response, the pricingPhases has a free trial and intro offer both, now the question is how to map different prices in the offerTags array?

**Comment by esathamzaj** [comment]
A tag set on a free trial offer is not being returned in my case, is anyone else facing this issue?

**Comment by matale** [comment]
> A tag set on a free trial offer is not being returned in my case, is anyone else facing this issue?

Offers which the user doesn't qualify for are not returned by the library so if you have a 7 day free trial and you set it to only users who have never had a subscription then once the user has had any subscription he will no longer get this offer in the response. I think this behavior should be highlighted in the docs. 
There also seems to be no way to reset this for testing purposes which is a problem when developing.

Also the values returned don't update immediately when you add new tags, there is caching on the Play side for me it seems to take 2 hours and/or I need to clear the Play Store data in phone settings.

**Comment by OhPeterPan** [comment]
> billingCycleCount

How to understand billingCycleCount, Google explained :Number of cycles for which the billing period is applied, but can't understand

**Comment by matale** [comment]
> billingCycleCount

`For example, for formattedPrice $6.99 and billingPeriod P1M, if billingCycleCount is 2, the user will be charged $6.99/month for 2 months. `
https://developer.android.com/reference/com/android/billingclient/api/ProductDetails.PricingPhase#getBillingCycleCount()
