### ISSUE TITLE
Find specific product based on purchase data

### ISSUE THREAD

**Issue by Dzejrin** [android/play-billing-samples#538]
Is there a way to find out which base plan or offer did user buy? 
I am able to find out a specific offer or base plan using queryPurchaseDetailsAsync and offerTags before launching the billing flow. However, once the user finishes the purchase flow in onPurchasesUpdated callback there seems to be no way to match Purchase object with specific offer.

**Comment by DineshNeupane** [comment]
@Dzejrin same issue. Did you manage to get any solution? The product can be identified from the Purchase object but not which offer of the product.

**Comment by Dzejrin** [comment]
> @Dzejrin same issue. Did you manage to get any solution? The product can be identified from the Purchase object but not which offer of the product. Would be so much relief if they provide purchase.getOfferId method.

Nope. I haven't found any solution so far.

**Comment by IsLery** [comment]
Same issue. What is also not clear is how to handle the change of offer for the same product. For example if the user has bought monthly offer of the product and wants to switch to yearly, how to find out what is the user's current offer.

**Comment by DanicMa** [comment]
We are facing the same problem. Because we cannot determine which offer the user bought, we cannot effectively offer changes of the plan/offer. This causes us a lot of troubles.

**Comment by tuan25abc** [comment]
According to Google, they create the new structure to reduce the large number of SKUs, so the sulution that using a single base plan per subscription looks weird.
 * `This allows you to sell the subscription in multiple ways and reduces operational costs by removing the need to create and manage an ever-increasing number of SKUs.` (https://android-developers.googleblog.com/2022/05/whats-new-in-google-play.html)

**Comment by matale** [comment]
Its definitely looks weird, while the new structure allows you to create and manage a lot of plans more easily when creating and possibly showing them to the user it doesn't look like they thought through the need to be able to identify what was bought later or they expect developers to be able to managed that themselves on the backend. 
I suspect this might come later, they will probably add the base plan and offer ids to the Purchase object at some stage.

**Comment by alazzam95** [comment]
is there any updates on this issue? how can we obtain the offer that the user purchased?

**Comment by PriyaSindkar** [comment]
I am facing the same issue. How to know which offer the user is currently subscribed to? I have also posted a [question](https://stackoverflow.com/questions/73703924/how-to-check-which-offer-a-user-is-currently-subscribed-to-in-play-billing-libra) on stackoverflow on this. But I think only the core team which has developed the library can answer us correctly.

**Comment by ai212983** [comment]
There is a [ticket](https://issuetracker.google.com/issues/236001071) on Google Issue tracker. It seems currently there is no way to know which plan is purchased. 

Proposed hack with plan ID in obfuscated Account/Profile id will not work if subscription is created outside the app, for example, [promo code](https://developer.android.com/google/play/billing/promo) is redeemed via Google Play.

Also currently there is no way to know when subscription will expire.

**Comment by EAdemov** [comment]
Same. There are a lot of unfinished features all around this V5 client.

**Comment by trambui09** [comment]
Thanks for the question, we've added an new offerDetails object that can help to identify the base plan and the offer post purchase. https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2#SubscriptionPurchaseLineItem for more details

**Comment by ai212983** [comment]
@trambui09 Have you read the ticket? Guys are talking about client, not about REST resources.

**Comment by PriyaSindkar** [comment]
@trambui09 Thank you for this update. Was this change applied to Android APIs as well?

**Comment by DanicMa** [comment]
@PriyaSindkar yes it was in a way, see changelog for the latest Billing library v5.1 https://developer.android.com/google/play/billing/release-notes#5-1x

**Comment by EvanPartidas** [comment]
> @PriyaSindkar yes it was in a way, see changelog for the latest Billing library v5.1 https://developer.android.com/google/play/billing/release-notes#5-1x

It looks like that's on the [`ProductDetails`](https://developer.android.com/reference/com/android/billingclient/api/ProductDetails) object and NOT on the [`Purchase`](https://developer.android.com/reference/com/android/billingclient/api/Purchase) object.  

There still seems to be no way to retrieve the Subscription info OfferIds nor Base Plans using Google Play Billling v7.

If you're in Java, you can instead use the [JavaClient](https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-androidpublisher/v3).

For Expo / React-Native it doesn't seem like there's a way to call the AndroidPublisher API directly from a React Native Client yet. As such, there's no way to retrieve the Offer Id or Base Plan for a Purchase with current libraries (react-native-iap for example). If this changes in the future or I'm wrong, please reply so others can find the information!
