### ISSUE TITLE
Response Code: FEATURE_NOT_SUPPORTED, Debug Message: Client does not support ProductDetails.

### ISSUE THREAD

**Issue by sidcpatel** [android/play-billing-samples#539]
I am testing the new billing client sample code on Android 11 simulator.

I encountered this error.

My app is compiled using SDK version 32 and using latest build tools.

I don't see any documentation about ProductDetails feature being not supported in older Android versions. Should we keep using SkuDetails and only use ProductDetails for devices with Android 31 or higher?

**Comment by naixx** [comment]
@sidcpatel so what do you do with Adroid below 31?

**Comment by sidcpatel** [comment]
Google Play Store 31.7.16 is compatible with Android 4/5. Hence, we can expect that users will be able to update their play store.
