### ISSUE TITLE
this.playDeveloperApiClient.purchases.subscriptionsv2.get | Server error: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by sassejlle** [android/play-billing-samples#544]
I'm implementing the ClassyTaxiAppKotlin + ClassyTaxiServer project but without success.

I followed all the steps in the tutorial.

Apparently the ClassyTaxiAppKotlin android app is functional, processes the subscription purchase order and sends the information to the CLOUD FUNCTIONS, but does not receive the purchase registration/confirmation.

In my understanding, upon receiving the payment confirmation, PLAY STORE must send this confirmation to the ClassyTaxiServer server so that the server returns the registration/confirmation of the purchase and grants access to the ClassyTaxiAppKotlin application.

So when confirming payment in ClassyTaxiAppKotlin app, I notice that I get some logs in firebase functions, but the registration/confirmation of payment doesn't complete due to a server error (500):
**_E/RemoteServerFunction: Failed to call API (Error code: 500) - {"status":500,"error":"not-found","message":"Cannot read property 'get' of undefined"}_**

Note: service-account.json is already configured

**Code where the error points: src/PurchasesManager.ts**
>    private async querySubscriptionPurchaseWithTriggerV2(packageName: string, product: string, purchaseToken: string, triggerNotificationType?: NotificationType): Promise<SubscriptionPurchaseV2> {
>      const apiResponseV2 = await new Promise((resolve, reject) => {
>        this.playDeveloperApiClient.purchases.subscriptionsv2.get({   <<<==== ERROR
>          packageName: packageName,
>          token: purchaseToken
>        }, (err, result) => {
>          if (err) {
>            reject(this.convertPlayAPIErrorToLibraryError(err));
>          } else {
>            resolve(result.data);
>          }
>        })
>      });
> 

**LOGS Firebase Functions**
> 6:55:57.537 PM subscription_register_v2 Function execution started
> 6:55:59.817 PM subscription_register_v2 Server error: Cannot read property 'get' of undefined
> 6:55:59.825 PM subscription_register_v2 Function execution took 2289 ms, finished with status code: 500
> 

**LOGS Android Studio**
> D/OkHttp: --> PUT https://us-central1-postosgnv.cloudfunctions.net/subscription_register_v2 http/1.1 (437-byte body)
> D/OkHttp: <-- 500  https://us-central1-postosgnv.cloudfunctions.net/subscription_register_v2 (2661ms, 86-byte body)
> E/RemoteServerFunction: Failed to call API (Error code: 500) - {"status":500,"error":"not-found","message":"Cannot read property 'get' of undefined"}
> 

UPDATE: Apparently the problem is in the **playDeveloperApiClient** that is not accepting the **purchases.subscriptionsv2.get** method, because I tested it using the **purchases.subscriptions.get** method and it worked.

**Comment by pyman2** [comment]
Try inserting subscriptionId after package Name

 packageName: packageName,
         subscriptionId: product,
         token: purchaseToken

**Comment by sassejlle** [comment]
Thanks for your response.

Sorry, my mistake. The code tested already contained the subscriptionId: product, I just copied the wrong code, but I already corrected it in the question above.

The error persists, but, apparently the problem is in the **playDeveloperApiClient** that is not accepting the **purchases.subscriptionsv2.get** method, because I tested it using the **purchases.subscriptions.get** method and it worked.

E/RemoteServerFunction: Failed to call API (Error code: 500) - {"status":500,"error":"not-found","message":"Cannot read property 'get' of undefined"}

**Comment by sassejlle** [comment]
Thanks for your response.

I tested with your suggestion but the error persists, but apparently the problem is in the playDeveloperApiClient that is not accepting the purchases.subscriptionsv2.get method, because I tested it using the purchases.subscriptions.get method and it worked.

E/RemoteServerFunction: Failed to call API (Error code: 500) - {"status":500,"error":"not-found","message":"Cannot read property 'get' of undefined"}

**Comment by kmansoft** [comment]
Same here. Trying to update my server side validation code from Subscription v1 to v2 and getting "internal error" from Google's servers.

```
	gservice, err := androidpublisher.NewService(context.Background(), option.WithTokenSource(source))
...
		call := gservice.Purchases.Subscriptionsv2.Get(rq.PackageName, item.Token)
		purchase, err := call.Do()
```

After `call.Do()` the error is `Internal error encountered.`

Please advise.

**Comment by kmansoft** [comment]
If I use the Google API explorer here: https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2 ...

... then I get "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console"

But the project *is* linked in Google Play Developer Console.

**Comment by kmansoft** [comment]
More info. I recently moved the app to a different developer account. Relinked the Google Cloud service account in Google Play Console and gave permissions.

If I use `Purchases.Subscriptions.Get` v1, the error is `The current user has insufficient permissions to perform the requested operation.`

According to this:

https://stackoverflow.com/a/52705172/2342806

The error is caused by the fact that I linked the Google Cloud account *after* the in-app subscription products already existed in Play console.

Is that so? I cannot re-create the subscriptions because I already have existing users.

Can this be fixed please - so that project linking can come *after* the subscriptions already exist without causing the permissions error?

**Comment by devonthomas35** [comment]
Is there ANY update on this? By reverting to `Purchases.Subscriptions.Get` I get a different exception

**Comment by devonthomas35** [comment]
I resolved this by updating the GoogleApis package in the package.json from  `"googleapis": "^67.0.0"` -> `"googleapis": "105.0.0"`

**Comment by sassejlle** [comment]
> I resolved this by updating the GoogleApis package in the package.json from `"googleapis": "^67.0.0"` -> `"googleapis": "105.0.0"`

Thanks devonthomas35, apparently this fixed the issue.
