### ISSUE TITLE
Firebase - subscription_register Finished with status code: 404

### ISSUE THREAD

**Issue by Wingx2** [android/play-billing-samples#560]
Hello ! 
I have a problem with firebase and no ideas , App seems to be able to communicate with firebase but have some error...
What did I miss?

**Firebase functions Log said**
subscription_register
-Function execution took 14 ms. Finished with status code: 404
-Cannot read property 'get' of undefined
![FireBase](https://user-images.githubusercontent.com/69433565/180853582-870efa4b-323f-4a29-a654-53a6f06af22f.PNG)

**Android studio Log said**
-Subscription server error= NOT_FOUND
-Invalid SKU or purchase token during registration
![AndroidStudio](https://user-images.githubusercontent.com/69433565/180854696-b9c8d9f7-4e2d-4d89-96fb-58cad9bee2ee.PNG)

** set BASIC_SKU, PREMIUM_SKU in Constants.java**
![AndroidStudioConstants](https://user-images.githubusercontent.com/69433565/180853401-2c935242-01bd-4e85-a2c5-4fccf62b9014.PNG)

**Google Play Subscription**
![PLAYsubscription](https://user-images.githubusercontent.com/69433565/180853539-69e87d6d-a82b-4abe-853e-b7d8bc959849.PNG)

Thanks
Wing

**Comment by Wingx2** [comment]
I try to Deploy Backend Server again, but there is an error!

![CmdError](https://user-images.githubusercontent.com/69433565/181313724-b89de3d4-f993-4cf4-b18c-29e78e6a5fc1.PNG)

Run **firebase functions:log** for more information , am i missing something?
![CmdError2](https://user-images.githubusercontent.com/69433565/181315309-e4991c0b-ea42-409f-b9b5-e16f297260b2.PNG)

Thanks !

**Comment by Wingx2** [comment]
![CmdError4](https://user-images.githubusercontent.com/69433565/181348153-bee560eb-bd0d-473c-a152-c9ba46aaf99d.PNG)

**Comment by matale** [comment]
Get the full firebase error message not just the Android one.  First try expanding those error messages and see what is there, if that's not enough then add more logging to the server code.

![image](https://user-images.githubusercontent.com/1497221/181602463-cae83abc-e8e2-4c5b-85ba-e6d3e38df54b.png)

**Comment by Wingx2** [comment]
Thanks for your reply!

I found this message
> Callable request verification passed {"verifications":{"app":"MISSING","auth":"VALID"}}

enough to find the problem? and no other extensions were found.

![CmdError6](https://user-images.githubusercontent.com/69433565/181609553-96c7f4d7-a0a0-4640-8e85-19316502871d.PNG)

Thanks!

**Comment by matale** [comment]
Dont see much there. What you can try do is add more logging in the subscription_register function like so, you should be able to see these in the Firebase console. Keep adding more logs until something makes sense.

```
 export const subscription_register = functions.https.onCall(async (data, context) => {
   verifyAuthentication(context);

   const product = data.product;
   const token = data.token;
   
   //ADDITIONAL LOGGING
   console.log('product: ' + product)
   console.log('token: ' + token)
   console.log('PACKAGE_NAME: ' + PACKAGE_NAME)

   try {
     await playBilling.purchases().registerToUserAccount(
       PACKAGE_NAME,
       product,
       token,
       ProductType.SUBS,
       context.auth.uid
     );
   } catch (err) {
   
     //ADDITIONAL LOGGING
	 console.log(err)
	 
     console.error(err.message);
     switch (err.name) {
       case PurchaseUpdateError.CONFLICT: {
         throw new functions.https.HttpsError('already-exists', 'Purchase token already registered to another user');
       }
       case PurchaseUpdateError.INVALID_TOKEN: {
         throw new functions.https.HttpsError('not-found', 'Invalid token');
       }
       default: {
         throw new functions.https.HttpsError('internal', 'Internal server error');
       }
     }
   }
   
   //ADDITIONAL LOGGING
	console.log('No error returning.')
	
   return getSubscriptionsResponseObject(context.auth.uid);
 });
```

**Comment by Wingx2** [comment]
Hello, 

Solved!
Removed my firebase project , and re-Deploy Backend Server (firebase new project), no problem now!

Thanks !

**Comment by Wingx2** [comment]
> Dont see much there. What you can try do is add more logging in the subscription_register function like so, you should be able to see these in the Firebase console. Keep adding more logs until something makes sense.
> 
> ```
>  export const subscription_register = functions.https.onCall(async (data, context) => {
>    verifyAuthentication(context);
> 
>    const product = data.product;
>    const token = data.token;
>    
>    //ADDITIONAL LOGGING
>    console.log('product: ' + product)
>    console.log('token: ' + token)
>    console.log('PACKAGE_NAME: ' + PACKAGE_NAME)
> 
>    try {
>      await playBilling.purchases().registerToUserAccount(
>        PACKAGE_NAME,
>        product,
>        token,
>        ProductType.SUBS,
>        context.auth.uid
>      );
>    } catch (err) {
>    
>      //ADDITIONAL LOGGING
> 	 console.log(err)
> 	 
>      console.error(err.message);
>      switch (err.name) {
>        case PurchaseUpdateError.CONFLICT: {
>          throw new functions.https.HttpsError('already-exists', 'Purchase token already registered to another user');
>        }
>        case PurchaseUpdateError.INVALID_TOKEN: {
>          throw new functions.https.HttpsError('not-found', 'Invalid token');
>        }
>        default: {
>          throw new functions.https.HttpsError('internal', 'Internal server error');
>        }
>      }
>    }
>    
>    //ADDITIONAL LOGGING
> 	console.log('No error returning.')
> 	
>    return getSubscriptionsResponseObject(context.auth.uid);
>  });
> ```

Hello :

I had success with earlier versions, When I deployed the last version of play-billing-samples, a similar problem occurs **Finished with status code: 400** and I added console.log(...) to **subscription_status_v2** as you suggested

//ADDITIONAL LOGGING
'product: ' + product)
console.log('token: ' + token)
console.log('PACKAGE_NAME: ' + PACKAGE_NAME)

Notice log " product: undefined " this might be the problem,  where do I need to define product?
![0815](https://user-images.githubusercontent.com/69433565/184552629-af22c685-d119-417f-9095-073e4f77c9a4.PNG)

Thank you again!

**Comment by matale** [comment]
> subscription_register = functions.https.onCall

That does look like a problem, try logging the entire request object. 
console.log(request) or console.log(request.body)

Also on the Android side in ServerFunctionsImpl.kt function registerSubscription 
Log the product and token you are sending and check if it is valid

    override suspend fun registerSubscription(
        product: String,
        purchaseToken: String
    ): List<SubscriptionStatus> {
        Log.d("MY_TAG","product: $product token: $purchaseToken")

Possibly the product is not being sent.

**Comment by Wingx2** [comment]
**On the Server side**
``` 
export const subscription_register_v2 = functions.https.onRequest(async (request, response) => {
return verifyFirebaseAuthIdToken(request, response)
     .then(async (decodedToken) => {
     const product = request.body.product;
     const uid = decodedToken.uid;
     const token = request.body.purchaseToken;
       
     //ADDITIONAL LOGGING
     console.log('product: ' + product);
     console.log('uid: ' + uid);
     console.log('token: ' + token);
     console.log('PACKAGE_NAME:' + PACKAGE_NAME);
     console.log('request:' +request)
     console.log('request.body:' +request.body)
	
	    
if (!token || !uid || !product) {
	 //ADDITIONAL LOGGING
	 console.log('throw:' + '!token || !uid || !product');
         throw new functions.https.HttpsError('invalid-argument', 'Missing required parameters!');	
 }
````


**On the Android side**
````  
public void registerSubscription(String sku, String purchaseToken) {
        Log.d("wwTAG", "SFI- registerSubscription() sku / purchaseToken= "+ sku +" / "+ purchaseToken);
        final String method = "registerSubscription";
        SubscriptionStatus data = new SubscriptionStatus();
        data.setSku(sku);
        data.setPurchaseToken(purchaseToken);
        pendingRequestCounter.incrementRequestCount();
        retrofitClient.getService().registerSubscription(data).enqueue(new RetrofitResponseHandlerCallback<SubscriptionStatusList>(method, pendingRequestCounter) {
            
@Override
 protected void onSuccess(SubscriptionStatusList response) {
                Log.d("wwTAG", "SFI- registerSubscription():onSuccess = "+response);
                onSuccessfulSubscriptionCall(response, subscriptions);
            }

 @Override
 protected void onError(int errorCode, @Nullable String errorMessage) {
     Log.d("wwTAG", "SFI- registerSubscription():onError = "+errorCode+" / "+errorMessage);
`````

**Comment by Wingx2** [comment]
On the Android side, I noticed that SubscriptionStatus Data(Class) provides data to Server, 

`SubscriptionStatus data = new SubscriptionStatus();` 
`data.setSku(sku);`
`data.setPurchaseToken(purchaseToken);`


but I refer to SubscriptionStatus Data(Class), it seems that there is no variable suitable for "product" added to send to Server!
Does this mean that this example doesn't work?

**SubscriptionStatus.java**
https://github.com/android/play-billing-samples/blob/main/ClassyTaxiJava/app/src/main/java/com/sample/android/classytaxijava/data/SubscriptionStatus.java

**Comment by Wingx2** [comment]
It not same issue now, i will close this topic.

**Comment by Wingx2** [comment]
It not same issue now, i will end this topic.

**Comment by Wingx2** [comment]
It not same issue now, i will end this topic, Thanks
