### ISSUE TITLE
How to get all products

### ISSUE THREAD

**Issue by donadoo** [android/play-billing-samples#565]
```
        List<QueryProductDetailsParams.Product> productList = new ArrayList<>();
        QueryProductDetailsParams.Product product = QueryProductDetailsParams.Product.newBuilder()
                .setProductId("test01")
                .setProductType(BillingClient.ProductType.INAPP)
                .build();
        productList.add(product);
        QueryProductDetailsParams queryProductDetailsParams =
                QueryProductDetailsParams.newBuilder()
                        .setProductList(productList)
                        .build();
```
need product id param, how to get all products from billing library?

**Comment by matale** [comment]
You need to create a QueryProductDetailsParams for each product and add them all to the product list, either one by one or do a loop like in BillingClientLifecycle.kt queryProductDetails()

**Comment by donadoo** [comment]
> 

Yes, but I meas how to get all products from play console. for example, if add new product from play console, app do not have the new product id, and then could not get this new product details from  queryProductDetails()

seems to get from https://developers.google.com/android-publisher/api-ref/rest/v3/inappproducts/list for this?

**Comment by matale** [comment]
You shouldn't use that API in the mobile App, you can use that on your backend and send the list of products to your App which can then use it to get the products from billing library.

**Comment by fy310518** [comment]
> You shouldn't use that API in the mobile App, you can use that on your backend and send the list of products to your App which can then use it to get the products from billing library.

Can you help me look at the problem of # 587?
