### ISSUE TITLE
received Google order id not start with GPA.

### ISSUE THREAD

**Issue by donadoo** [android/play-billing-samples#576]
I found something strange like, the Order ID received from `onPurchasesUpdated` for that purchase is found as
`1234567891234567891.1234567891234567`

1. why some order id not start with 'GPA.'? 
2. and this order is valid?

**Comment by Ayagikei** [comment]
These should be fake orders.
Some crackers may try to bypass the local checksum.

You can follow the server-side verification method in the document to ensure that the order is valid.

**Comment by dasparkgames** [comment]
same is happening for me, please share solution if found because this makes it impossible to verify MMP data!

**Comment by donadoo** [comment]
> These should be fake orders. Some crackers may try to bypass the local checksum.
> 
> You can follow the server-side verification method in the document to ensure that the order is valid.

@Ayagikei I want to know how to mock this orders? From my app, these orders happens every day

**Comment by donadoo** [comment]
> same is happening for me, please share solution if found because this makes it impossible to verify MMP data!

@dyllydyllyber me too

**Comment by Ayagikei** [comment]
> > These should be fake orders. Some crackers may try to bypass the local checksum.
> > You can follow the server-side verification method in the document to ensure that the order is valid.
> 
> @Ayagikei I want to know how to mock this orders? From my app, these orders happens every day

Maybe it's from something like _LuckyPatcher_.

If you have a service side, use the following API to ensure the token and order are valid:
[For one-time product](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.products/get)
[For subscriptions](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2/get)

If it is an illegal order, you should receive a 400 error response code; if it is a valid order, you can check the order information.

If you don't have a server, maybe you can try checking the order id locally. But without inserting Google will change the order format, which is not recommended.

**Comment by stephanedupont** [comment]
> These should be fake orders. Some crackers may try to bypass the local checksum.
> 
> You can follow the server-side verification method in the document to ensure that the order is valid.

To anyone stumbling upon this: warning, some order numbers are not starting with GPA but are perfectly valid. They are not common, and indeed, most are fake orders, but not 100%. Some can be found in your developer console and can be checked with the verification API.

**Comment by trambui09** [comment]
Thank you for this question. Not all purchases are guaranteed to generate an orderId. As others have mentioned, the best practice to fight possible fraud and abuse is to follow server-side verification methods detailed in our [public documentation](https://developer.android.com/google/play/billing/security).
