### ISSUE TITLE
How to identify base plans and offers from "Purchase" objects/queryPurchasesAsync?

### ISSUE THREAD

**Issue by novag** [android/play-billing-samples#586]
The issue of not being able to identify base plans and offers from the purchases API and the Play Billing Library's "queryProductDetails" method has been resolved in recent weeks as mentioned by @trambui09 in #547 and #548.

However, as I understand it, there is still no way to get to the base plan or offer from a "Purchase" object, e.g. after calling "queryPurchasesAsync". Is there any other way in the Play Billing Library to find the base plan after a purchase?

Thanks.

**Comment by matale** [comment]
Don't think so, you would need to save this info to your won backend or in the app at the time of purchase.

**Comment by trambui09** [comment]
Hi @novag, your understanding is correct. And as @matale mentioned, to easily identify the base plans and offers, please use the [SubscriptionPurchaseV2](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2#SubscriptionPurchaseLineItem) API

**Comment by ManishAmdocs** [comment]
Is there any way to get the base plan Id, in our application? I noticed that we only have the order ID and the product id, but I need to get the base plan id of the consumed subscription.

**Comment by EAdemov** [comment]
I was wondering the same thing. Seems like V6 comes with some improvements but still lacks a lot of basic functionalities and data.
