### ISSUE TITLE
How do I check if a subscription has expired

### ISSUE THREAD

**Issue by OhPeterPan** [android/play-billing-samples#588]
When android confirms whether there is a valid subscription, I use queryPurchasesAsync() to get the transaction, but in the testing phase, the subscription that has expired can still be obtained, which makes me very distressed. How can I get the subscription status correctly? please help me! thanks

**Comment by matale** [comment]
You need to use the backend API pretty much, queryPurchasesAsync on the device seems to be heavily cached and will therefore not give realtime results.

**Comment by OhPeterPan** [comment]
> You need to use the backend API pretty much, queryPurchasesAsync on the device seems to be heavily cached and will therefore not give realtime results.

Thank You

**Comment by trambui09** [comment]
Hi @OhPeterPan, please refer to [this section](https://developer.android.com/google/play/billing/subscriptions#expirations) of the public documentation to check if a subscription has expired.

**Comment by OhPeterPan** [comment]
> Thank You

**Comment by OhPeterPan** [comment]
> Hi @OhPeterPan, please refer to [this section](https://developer.android.com/google/play/billing/subscriptions#expirations) of the public documentation to check if a subscription has expired.

Thank You
