### ISSUE TITLE
What is the difference between BillingClient.queryPurchasesAsync() vs Purchases.subscriptionsv2:get

### ISSUE THREAD

**Issue by desmondlee95700** [android/play-billing-samples#591]
Can i know what is the difference between BillingClient.queryPurchasesAsync() vs Purchases.subscriptionsv2:get ?

I see the documentation for https://developer.android.com/google/play/billing/integrate is using BillingClient. 
Can I know when and why need to use Purchases.subscriptionsv2:get  Google API ?

Thank you and much appreaciated

**Comment by crocodile** [comment]
I haven't used `Purchases.subscriptionsv2:get`yet, but isn't that for a [server-to-server call](https://developer.android.com/google/play/billing/subscriptions#lifecycle) that's part of the [Google Developer API](https://developer.android.com/google/play/developer-api) , as opposed to `BillingClient.queryPurchasesAsync()`which you should use in the mobile app?

**Comment by desmondlee95700** [comment]
> I think `Purchases.subscriptionsv2:get` is for [server-to-server handling of the subscription lifecycle](https://developer.android.com/google/play/billing/subscriptions#lifecycle) with the [Google Play Developer API](https://developer.android.com/google/play/developer-api), whereas `BillingClient.queryPurchasesAsync()` is what you would use in the mobile app.

Thanks for the update. So if I want to send some details to backend, then I have to utilize `Purchase.subscriptionsv2.get` ?

**Comment by matale** [comment]
If you have a server from which you want to get subscription info from Play you should use the web API if you want to access the purchase info for the user on the device you should use the billingClient methods, if you then want to send this info to your backend that is up to you. 

You should not access the web API from the device because you will need to include the access keys in the app which is big security issue, access keys should remain on your server only.

The API also has much more info.

**Comment by desmondlee95700** [comment]
> If you have a server from which you want to get subscription info from Play you should use the web API if you want to access the purchase info for the user on the device you should use the billingClient methods, if you then want to send this info to your backend that is up to you.
> 
> You should not access the web API from the device because you will need to include the access keys in the app which is big security issue, access keys should remain on your server only.
> 
> The API also has much more info.

Thanks for the replies and much appreciated.
