### ISSUE TITLE
Querying multiple products consisting of both subscriptions and one-time products fails

### ISSUE THREAD

**Issue by crocodile** [android/play-billing-samples#592]
I am trying to fetch the available subscriptions and on-time products as per the [official documentation](https://developer.android.com/google/play/billing/integrate#show-products). The code is based on the ClassyTaxiAppKotlin project's [BillingClientLifecycle.kt](https://github.com/android/play-billing-samples/blob/main/ClassyTaxiAppKotlin/app/src/main/java/com/example/subscriptions/billing/BillingClientLifecycle.kt) class with small modifications.

So I defined my product ids and their types:
```
enum class BillingProducts(val productId: String, val type: String) {
   SOMETHING_PERPETUAL("something_perpetual", BillingClient.ProductType.INAPP),
   SOME_SUBSCRIPTION("some_subscription", BillingClient.ProductType.SUBS)
}
```

I started a query as follows:
```
fun BillingClientLifecycle.queryProductDetails() {

val productList: MutableList<QueryProductDetailsParams.Product> = arrayListOf()
for (product in enumValues<BillingProducts>()) {
    productList.add(
        QueryProductDetailsParams.Product.newBuilder()
            .setProductId(product.productId)
            .setProductType(product.type)
            .build()
    )
}

val params = QueryProductDetailsParams.newBuilder()
params.setProductList(productList).let { productDetailsParams ->
    this.billingClient.queryProductDetailsAsync(
        productDetailsParams.build(),
        MyProductDetailsResponseListener(this)
    )
}
```

The problem is, that the [ProductDetailsResponseListener](https://developer.android.com/reference/com/android/billingclient/api/ProductDetailsResponseListener) **callback is never called**, not even with an Error. I get nothing back.

----------------------

However if I change both billing products to the same type. For example:

```
SOMETHING_PERPETUAL("something_perpetual", BillingClient.ProductType.INAPP),
SOME_SUBSCRIPTION("some_subscription", BillingClient.ProductType.INAPP)
```
or

```
 SOMETHING_PERPETUAL("something_perpetual", BillingClient.ProductType.SUBS),
 SOME_SUBSCRIPTION("some_subscription", BillingClient.ProductType.SUBS)
```
then the callback returns fine with some of the products. (Obviously not with all of the products, because one of them now has the incorrect type defined in the query.)

I am using `com.android.billingclient:billing:5.1.0` testing on the SDK emulator running Android 13 with Google Play store version 33.5.16-21

**Comment by donadoo** [comment]
![image](https://user-images.githubusercontent.com/44422450/208389040-7ae55524-60b6-4097-87b4-c252baae7ccb.png)
All products should be of the same product type

**Comment by crocodile** [comment]
Thanks. The thread was silently crashing and I didn't notice that.

It's still a very disappointing API limitation though 😞

**Comment by donadoo** [comment]
@matale 
Does this api could support query products details with `inapp` and `subs` one time?

**Comment by william-ferguson-au** [comment]
This limitation of the API is extremely disappointing for these reasons

1. It is not documented  in the API or alluded to anywhere that I could find in the Play Billing doco.
2. QueryProductDetailsParams#setProductList() is invariably called from BillingClientStateListener#onBillingSetupFinished() once you have connected to PlayBilling. But the thread that calls #onBillingSetupFinished does not catch and log the IllegalArgumentException. It just swallows the Exception, so the developer has no idea what is going on.

Do better Google.
