### ISSUE TITLE
Why is the queryProductDetailsAsync result list empty?

### ISSUE THREAD

**Issue by xiaomeng3419** [android/play-billing-samples#608]
Why is the queryProductDetailsAsync result list empty on the internal test track in version 5.1.0? Subscription product configurations are correct in Google Play

**Comment by lfd547** [comment]
how do you fixed this? I have the same problem.

**Comment by elpatopedraza** [comment]
Hey, same here. Any solution to this? I'm using com.android.billingclient:billing:6.1.0, my test licensing and subscriptions are configured correctly but the client is returning an empty list when queryProductDetailsAsync is invoked.
