### ISSUE TITLE
Why is the queryProductDetailsAsync result list empty?

### ISSUE THREAD

**Issue by zzspuck** [android/play-billing-samples#617]
BillingClient version 5.1.0
I create an  app to google play, uploaded it to internal testing, 
 added subscription products got the product details through the product id but response Code 0  productDetailsList empty

I searched from Stackoverflow have answered  Draft app testing is no longer supported for testing in-app purchases. Hence you are getting an empty response.

You need to move them to alpha or beta channel

Is this correct？

**Comment by zzspuck** [comment]
thanks  the reason is  My test account can't pay

**Comment by ninh-huynh** [comment]
> thanks the reason is My test account can't pay

Can you tell more clearly the root cause? I met the same problem but on production with some users. The method queryProductionDetailsAsync always returns an empty list.

**Comment by darkharov** [comment]
Problem still exist. Version 6.0.1

I uploaded a test bundle to internal testing.
I added a gmail account to the license testers. (RESPOND_NORMALLY)
I added valid bank card with balance to this gmail account
I added this gmail account to internal testing
I accepted the invite
**A real device**
I installed the test version from google play on a real device.
This gmail is the main account. (The second account is NOT a tester and has a country where this app is not available)
Log cat logs: Response Code: OK, Debug Message: , products: []
**An emulator**
I installed the test version from google play on an emulator
Log cat logs: Response Code: OK, Debug Message: , products: []

**Comment by tafelnl** [comment]
@darkharov I've also verified all the stuff you mentioned for my use-case. But I'm still stuck. Did you figure it out eventually?

**Comment by tafelnl** [comment]
Actually I finally got it working by simply waiting for a little more. Apparently a lot of these changes are not instant, and take a few minutes/hours to process and propagate

**Comment by dominicoder** [comment]
For anyone else that's coming here from a Google search and not having any luck with the other comments, what finally worked for me was **signing the debug build with the release key** to match the build that's on Google Play testing track. You probably want to have the version codes match too.

Reference: after multiple days of searching and trying things, I came across this [10-year-old post](https://stackoverflow.com/a/22469253/1197251).

**Comment by htteng1976** [comment]
After adding the developer email into license testing option in Google Play Console, signing the debug apk with release key and confirm the applicationId is official (not staging), I finally got the non-empty productDetailsList from queryProductDetailsAsync().

Thanks for the messages from @wdtheprovider @dominicoder .
