### ISSUE TITLE
upgrade or downgrade  

### ISSUE THREAD

**Issue by ShwoTimeNow** [android/play-billing-samples#640]
billing v6:

Test environment:

FIrst buy:
productId=abc 
offerToken=offerToken1

Upgrade:
productId=abc
offerToken=offerToken2
oldPurchase=xxxxx

When I change plan, it will show:

"User is not eligible for this purchase"

why?

**Comment by matale** [comment]
It depends. 
Look through the other issues posted about upgrade/downgrade and see if anything rings a bell, if not you have to provide a lot more info like how the subscriptions are actually set up and how you are doing upgrade what are you passing as oldPurchase, proration mode etc.

**Comment by ShwoTimeNow** [comment]
fixed
