### ISSUE TITLE
why does 'not eligible for the free trial` show?

### ISSUE THREAD

**Issue by wangjianpeng** [android/play-billing-samples#659]
When I want to purchase week subscription , I saw a tip which is `You're not eligible for the free trial` , why does it show and how to hide it on the play console ?
![week_no_free_trial2](https://github.com/android/play-billing-samples/assets/4220174/482901c8-ddbe-410e-87ad-4baf6df989c0)

**Comment by matale** [comment]
Have you setup a free trial option for this subscription in play console?

**Comment by wangjianpeng** [comment]
> Have you setup a free trial option for this subscription in play console?

yes, I made it.
